export type AbpLocalizationResources = {
  "DisplayName:Abp.Localization.DefaultLanguage": "Default language";
  "Description:Abp.Localization.DefaultLanguage": "The default language of the application.";
};
export type AbpValidationResources = {
  "'{0}' and '{1}' do not match.": "'{0}' and '{1}' do not match.";
  "The {0} field is not a valid credit card number.": "The {0} field is not a valid credit card number.";
  "{0} is not valid.": "{0} is not valid.";
  "The {0} field is not a valid e-mail address.": "The {0} field is not a valid e-mail address.";
  "The {0} field only accepts files with the following extensions: {1}": "The {0} field only accepts files with the following extensions: {1}";
  "The field {0} must be a string or array type with a maximum length of '{1}'.": "The field {0} must be a string or array type with a maximum length of '{1}'.";
  "The field {0} must be a string or array type with a minimum length of '{1}'.": "The field {0} must be a string or array type with a minimum length of '{1}'.";
  "The {0} field is not a valid phone number.": "The {0} field is not a valid phone number.";
  "The field {0} must be between {1} and {2}.": "The field {0} must be between {1} and {2}.";
  "The field {0} must match the regular expression '{1}'.": "The field {0} does not match the requested format.";
  "The {0} field is required.": "The {0} field is required.";
  "The field {0} must be a string with a maximum length of {1}.": "The field {0} must be a string with a maximum length of {1}.";
  "The field {0} must be a string with a minimum length of {2} and a maximum length of {1}.": "The field {0} must be a string with a minimum length of {2} and a maximum length of {1}.";
  "The {0} field is not a valid fully-qualified http, https, or ftp URL.": "The {0} field is not a valid fully-qualified http, https, or ftp URL.";
  "The field {0} is invalid.": "The field {0} is invalid.";
  "The value '{0}' is invalid.": "The value '{0}' is invalid.";
  "The field {0} must be a number.": "The field {0} must be a number.";
  "The field must be a number.": "The field must be a number.";
  "ThisFieldIsNotAValidCreditCardNumber.": "This field is not a valid credit card number.";
  "ThisFieldIsNotValid.": "This field is not valid.";
  "ThisFieldIsNotAValidEmailAddress.": "This field is not a valid e-mail address.";
  "ThisFieldOnlyAcceptsFilesWithTheFollowingExtensions:{0}": "This field only accepts files with the following extensions: {0}";
  "ThisFieldMustBeAStringOrArrayTypeWithAMaximumLengthOf{0}": "This field must be a string or array type with a maximum length of '{0}'.";
  "ThisFieldMustBeAStringOrArrayTypeWithAMinimumLengthOf{0}": "This field must be a string or array type with a minimum length of '{0}'.";
  "ThisFieldIsNotAValidPhoneNumber.": "This field is not a valid phone number.";
  "ThisFieldMustBeBetween{0}And{1}": "This field must be between {0} and {1}.";
  "ThisFieldMustBeGreaterThanOrEqual{0}": "This field must be greater than or equal to {0}.";
  "ThisFieldMustBeLessOrEqual{0}": "This field must be less than or equal to {0}.";
  "ThisFieldMustMatchTheRegularExpression{0}": "This field must match the regular expression '{0}'.";
  "ThisFieldIsRequired.": "This field is required.";
  "ThisFieldMustBeAStringWithAMaximumLengthOf{0}": "This field must be a string with a maximum length of {0}.";
  "ThisFieldMustBeAStringWithAMinimumLengthOf{1}AndAMaximumLengthOf{0}": "This field must be a string with a minimum length of {1} and a maximum length of {0}.";
  ThisFieldIsNotAValidFullyQualifiedHttpHttpsOrFtpUrl: "This field is not a valid fully-qualified http, https, or ftp URL.";
  "ThisFieldIsInvalid.": "This field is invalid.";
};
export type AbpAuditLoggingResources = {
  "Permission:AuditLogging": "Audit logging";
  "Permission:AuditLogs": "Audit logs";
  "Menu:AuditLogging": "Audit logs";
  AuditLogs: "Audit logs";
  HttpStatus: "HTTP status";
  HttpMethod: "HTTP method";
  HttpMethodFilter: "HTTP method filter";
  HttpRequest: "HTTP Request";
  User: "User";
  UserNameFilter: "User filter";
  HasException: "Has exception";
  IpAddress: "IP address";
  Time: "Time";
  Date: "Date";
  Duration: "Duration";
  Detail: "Detail";
  Overall: "Overall";
  Actions: "Actions";
  ClientIpAddress: "Client IP Address";
  ClientName: "Client Name";
  BrowserInfo: "Browser Info";
  Url: "URL";
  UserName: "User name";
  TenantImpersonator: "Tenant Impersonator";
  UserImpersonator: "User Impersonator";
  UrlFilter: "URL filter";
  Exceptions: "Exceptions";
  Comments: "Comments";
  HttpStatusCode: "HTTP status code";
  HttpStatusCodeFilter: "HTTP status code filter";
  ServiceName: "Service";
  MethodName: "Method";
  CorrelationId: "Correlation Id";
  ApplicationName: "Application name";
  ExecutionDuration: "Duration";
  ExtraProperties: "Extra properties";
  MaxDuration: "Max. duration";
  MinDuration: "Min. duration";
  MinMaxDuration: "Duration (Min. - Max.)";
  "{0}Milliseconds": "{0} milliseconds";
  ExecutionTime: "Time";
  Parameters: "Parameters";
  EntityTypeFullName: "Entity Type Full Name";
  Entity: "Entity";
  ChangeType: "Change type";
  ChangeTime: "Time";
  NewValue: "New value";
  OriginalValue: "Original value";
  PropertyName: "Property name";
  PropertyTypeFullName: "Property Type Full Name";
  Yes: "Yes";
  No: "No";
  Changes: "Changes";
  AverageExecutionDurationInLogsPerDay: "Average execution duration";
  AverageExecutionDurationInMilliseconds: "Average execution duration in milliseconds";
  ErrorRateInLogs: "Error rate in logs";
  Success: "Success";
  Fault: "Fault";
  NoChanges: "No change(s)";
  EntityChanges: "Entity changes";
  EntityId: "Entity Id";
  EntityChangeStartTime: "Min change date";
  EntityChangeEndTime: "Max change date";
  EntityHistory: "Entity history";
  DaysAgoTitle: "{0} {1}.";
  DaysAgoWithUserTitle: "{0} {1} by {2}.";
  Created: "Created";
  Updated: "Updated";
  Deleted: "Deleted";
  ChangeHistory: "Change history";
  FullChangeHistory: "Full change history";
  ChangeDetails: "Change details";
  DurationMs: "Duration (ms)";
  StartDate: "Start date";
  EndDate: "End date";
  "Feature:AuditLoggingGroup": "Audit logging";
  "Feature:AuditLoggingEnable": "Enable audit logging page";
  "Feature:AuditLoggingEnableDescription": "Enable audit logging page in the application.";
  "Feature:AuditLoggingSettingManagementEnable": "Enable audit log setting management";
  "Feature:AuditLoggingSettingManagementEnableDescription": "Enable the configuration of the audit log setting management within the application.";
  InvalidAuditLogDeletionSettings: "Invalid audit log deletion settings. If deletion is enable, the period should be greater than 0 days.";
  AuditLogSettingsGeneral: "General";
  AuditLogSettingsGlobal: "Global";
  "DisplayName:IsPeriodicDeleterEnabled": "Enable clean up service system wide";
  "Description:IsPeriodicDeleterEnabled": "If this option is disabled the periodic deleter won't work. Audit logs won't be deleted automatically.";
  "DisplayName:GlobalIsExpiredDeleterEnabled": "Enable clean up service for all tenants and host";
  "Description:GlobalIsExpiredDeleterEnabled": "If this option is enabled all the tenants and the host expired items will be deleted automatically unless it has a specific setting.";
  "DisplayName:IsExpiredDeleterEnabled": "Enable clean up service";
  "Description:IsExpiredDeleterEnabled": "If this option is enabled the expired items will be deleted automatically.";
  "DisplayName:ExpiredDeleterPeriod": "Expired item deletion period";
  "Description:ExpiredDeleterPeriod": "Set the number of days after which expired items will be automatically deleted.";
  ExpiredDeleterPeriodUnit: "day(s)";
  AuditLogsBeforeXWillBeDeleted: "Audit logs before {0} will be deleted.";
};
export type AbpTimingResources = {
  "DisplayName:Abp.Timing.Timezone": "Timezone";
  "Description:Abp.Timing.Timezone": "Application time zone";
};
export type AbpFeatureManagementResources = {
  Features: "Features";
  NoFeatureFoundMessage: "There isn't any available feature.";
  ManageHostFeatures: "Manage host features";
  ManageHostFeaturesText: "You can manage the host side features by clicking the following button.";
  "Permission:FeatureManagement": "Feature management";
  "Permission:FeatureManagement.ManageHostFeatures": "Manage host features";
  "Volo.Abp.FeatureManagement:InvalidFeatureValue": "{0} feature value is not valid!";
  "Menu:FeatureManagement": "Feature management";
  ResetToDefault: "Reset to default";
  ResetedToDefault: "Reseted to default";
  AreYouSure: "Are you sure?";
  AreYouSureToResetToDefault: "Are you sure to reset to default?";
};
export type AbpMultiTenancyResources = {
  TenantNotFoundMessage: "Tenant not found!";
  TenantNotFoundDetails: "There is no tenant with the tenant id or name: {0}";
  TenantNotActiveMessage: "Tenant is not active!";
  TenantNotActiveDetails: "The tenant is not active with the tenant id or name: {0}";
};
export type AbpFeatureResources = {
  "Volo.Feature:010001": "Feature is not enabled: {FeatureName}";
  "Volo.Feature:010002": "Required features are not enabled. All of these features must be enabled: {FeatureNames}";
  "Volo.Feature:010003": "Required features are not enabled. At least one of these features must be enabled: {FeatureNames}";
};
export type AbpIdentityResources = {
  "Menu:IdentityManagement": "Identity management";
  Users: "Users";
  NewUser: "New user";
  UserName: "User name";
  Surname: "Surname";
  EmailAddress: "Email address";
  PhoneNumber: "Phone number";
  UserInformations: "User Information";
  "DisplayName:IsDefault": "Default";
  "DisplayName:IsStatic": "Static";
  "DisplayName:IsPublic": "Public";
  Roles: "Roles";
  Password: "Password";
  PersonalInfo: "My profile";
  PersonalSettings: "Personal settings";
  UserDeletionConfirmationMessage: "Are you sure you want to delete the user '{0}'?";
  RoleDeletionConfirmationMessage: "Are you sure you want to delete the role '{0}'?";
  "DisplayName:RoleName": "Role name";
  "DisplayName:UserName": "User name";
  "DisplayName:Name": "Name";
  "DisplayName:Surname": "Surname";
  "DisplayName:Password": "Password";
  "DisplayName:Email": "Email";
  "DisplayName:PhoneNumber": "Phone number";
  "DisplayName:TwoFactorEnabled": "Two-factor authentication enabled";
  "DisplayName:IsActive": "Active";
  "DisplayName:LockoutEnabled": "Account lockout";
  NewRole: "New role";
  RoleName: "Role name";
  CreationTime: "Creation time";
  Permissions: "Permissions";
  "DisplayName:CurrentPassword": "Current password";
  "DisplayName:NewPassword": "New password";
  "DisplayName:NewPasswordConfirm": "Confirm new password";
  PasswordChangedMessage: "Your password has been changed successfully.";
  PersonalSettingsSavedMessage: "Your personal settings has been saved successfully.";
  "Volo.Abp.Identity:DefaultError": "An unknown failure has occurred.";
  "Volo.Abp.Identity:ConcurrencyFailure": "Optimistic concurrency check has been failed. The entity you're working on has modified by another user. Please discard your changes and try again.";
  "Volo.Abp.Identity:DuplicateEmail": "Email '{0}' is already taken.";
  "Volo.Abp.Identity:DuplicateRoleName": "Role name '{0}' is already taken.";
  "Volo.Abp.Identity:DuplicateUserName": "Username '{0}' is already taken.";
  "Volo.Abp.Identity:InvalidEmail": "Email '{0}' is invalid.";
  "Volo.Abp.Identity:InvalidPasswordHasherCompatibilityMode": "The provided PasswordHasherCompatibilityMode is invalid.";
  "Volo.Abp.Identity:InvalidPasswordHasherIterationCount": "The iteration count must be a positive integer.";
  "Volo.Abp.Identity:InvalidRoleName": "Role name '{0}' is invalid.";
  "Volo.Abp.Identity:InvalidToken": "Invalid token.";
  "Volo.Abp.Identity:InvalidUserName": "Username '{0}' is invalid, can only contain letters or digits.";
  InvalidUserName: "Username '{0}' is invalid.";
  "Volo.Abp.Identity:LoginAlreadyAssociated": "A user with this login already exists.";
  "Volo.Abp.Identity:PasswordMismatch": "Incorrect password.";
  "Volo.Abp.Identity:PasswordRequiresDigit": "Passwords must have at least one digit ('0'-'9').";
  "Volo.Abp.Identity:PasswordRequiresLower": "Passwords must have at least one lowercase ('a'-'z').";
  "Volo.Abp.Identity:PasswordRequiresNonAlphanumeric": "Passwords must have at least one non alphanumeric character.";
  "Volo.Abp.Identity:PasswordRequiresUpper": "Passwords must have at least one uppercase ('A'-'Z').";
  "Volo.Abp.Identity:PasswordTooShort": "Passwords must be at least {0} characters.";
  "Volo.Abp.Identity:PasswordRequiresUniqueChars": "Passwords must use at least {0} different characters.";
  "Volo.Abp.Identity:RoleNotFound": "Role {0} does not exist.";
  "Volo.Abp.Identity:UserAlreadyHasPassword": "User already has a password set.";
  "Volo.Abp.Identity:UserAlreadyInRole": "User already in role '{0}'.";
  "Volo.Abp.Identity:UserLockedOut": "User is locked out.";
  "Volo.Abp.Identity:UserLockoutNotEnabled": "Lockout is not enabled for this user.";
  "Volo.Abp.Identity:UserNameNotFound": "User {0} does not exist.";
  "Volo.Abp.Identity:UserNotInRole": "User is not in role '{0}'.";
  "Volo.Abp.Identity:PasswordConfirmationFailed": "Password does not match the confirm password.";
  "Volo.Abp.Identity:NullSecurityStamp": "User security stamp cannot be null.";
  "Volo.Abp.Identity:RecoveryCodeRedemptionFailed": "Recovery code redemption failed.";
  "Volo.Abp.Identity:010001": "You can not delete your own account!";
  "Volo.Abp.Identity:010002": "Can not set more than {MaxUserMembershipCount} organization unit for a user!";
  "Volo.Abp.Identity:010003": "Can not change password of an externally logged in user!";
  "Volo.Abp.Identity:010004": "There is already an organization unit with name {0}. Two units with same name can not be created in same level.";
  "Volo.Abp.Identity:010005": "Static roles can not be renamed.";
  "Volo.Abp.Identity:010006": "Static roles can not be deleted.";
  "Volo.Abp.Identity:010007": "You can't change your two factor setting.";
  "Volo.Abp.Identity:010008": "It's not allowed to change two factor setting.";
  "Volo.Abp.Identity:010009": "You can not delegate yourself.";
  "Volo.Abp.Identity:010021": "Name exist: '{0}'.";
  "Identity.OrganizationUnit.MaxUserMembershipCount": "Maximum allowed organization unit membership count for a user";
  ThisUserIsNotActiveMessage: "This user is not active.";
  "Permission:IdentityManagement": "Identity management";
  "Permission:RoleManagement": "Role management";
  "Permission:Create": "Create";
  "Permission:Edit": "Edit";
  "Permission:Delete": "Delete";
  "Permission:ChangePermissions": "Change permissions";
  "Permission:ManageRoles": "Managing roles";
  "Permission:UserManagement": "User management";
  "Permission:UserLookup": "User lookup";
  "DisplayName:Abp.Identity.Password.RequiredLength": "Required length";
  "DisplayName:Abp.Identity.Password.RequiredUniqueChars": "Required unique characters number";
  "DisplayName:Abp.Identity.Password.RequireNonAlphanumeric": "Required non-alphanumeric character";
  "DisplayName:Abp.Identity.Password.RequireLowercase": "Required lower case character";
  "DisplayName:Abp.Identity.Password.RequireUppercase": "Required upper case character";
  "DisplayName:Abp.Identity.Password.RequireDigit": "Required digit";
  "DisplayName:Abp.Identity.Password.ForceUsersToPeriodicallyChangePassword": "Force users to periodically change password";
  "DisplayName:Abp.Identity.Password.PasswordChangePeriodDays": "Password change period(days)";
  "DisplayName:Abp.Identity.Lockout.AllowedForNewUsers": "Enabled for new users";
  "DisplayName:Abp.Identity.Lockout.LockoutDuration": "Lockout duration(seconds)";
  "DisplayName:Abp.Identity.Lockout.MaxFailedAccessAttempts": "Max failed access attempts";
  "DisplayName:Abp.Identity.SignIn.RequireConfirmedEmail": "Require confirmed email";
  "DisplayName:Abp.Identity.SignIn.EnablePhoneNumberConfirmation": "Allow users to confirm their phone number";
  "DisplayName:Abp.Identity.SignIn.RequireConfirmedPhoneNumber": "Require confirmed phone number";
  "DisplayName:Abp.Identity.User.IsUserNameUpdateEnabled": "Allow users to change their usernames";
  "DisplayName:Abp.Identity.User.IsEmailUpdateEnabled": "Allow users to change their email addresses";
  "Description:Abp.Identity.Password.RequiredLength": "The minimum length a password must be.";
  "Description:Abp.Identity.Password.RequiredUniqueChars": "The minimum number of unique characters which a password must contain.";
  "Description:Abp.Identity.Password.RequireNonAlphanumeric": "If passwords must contain a non-alphanumeric character.";
  "Description:Abp.Identity.Password.RequireLowercase": "If passwords must contain a lower case ASCII character.";
  "Description:Abp.Identity.Password.RequireUppercase": "If passwords must contain a upper case ASCII character.";
  "Description:Abp.Identity.Password.RequireDigit": "If passwords must contain a digit.";
  "Description:Abp.Identity.Password.ForceUsersToPeriodicallyChangePassword": "Whether users are forced to periodically change their password.";
  "Description:Abp.Identity.Password.PasswordChangePeriodDays": "The number of days a user's password is valid for.";
  "Description:Abp.Identity.Lockout.AllowedForNewUsers": "Whether a new user can be locked out.";
  "Description:Abp.Identity.Lockout.LockoutDuration": "The duration a user is locked out for when a lockout occurs.";
  "Description:Abp.Identity.Lockout.MaxFailedAccessAttempts": "The number of failed access attempts allowed before a user is locked out, assuming lock out is enabled.";
  "Description:Abp.Identity.SignIn.RequireConfirmedEmail": "Whether a confirmed email address is required to sign in.";
  "Description:Abp.Identity.SignIn.EnablePhoneNumberConfirmation": "Whether the phoneNumber can be confirmed by the user.";
  "Description:Abp.Identity.SignIn.RequireConfirmedPhoneNumber": "Whether a confirmed telephone number is required to sign in.";
  "Description:Abp.Identity.User.IsUserNameUpdateEnabled": "Whether the username can be updated by the user.";
  "Description:Abp.Identity.User.IsEmailUpdateEnabled": "Whether the email can be updated by the user.";
  Details: "Details";
  CreatedBy: "Created by";
  ModifiedBy: "Modified by";
  ModificationTime: "Modification time";
  PasswordUpdateTime: "Password update time";
  LockoutEndTime: "Lockout end time";
  FailedAccessCount: "Failed access count";
  "Feature:IdentityGroup": "Identity";
  "Feature:TwoFactor": "Two factor behaviour";
  "Feature:TwoFactorDescription": "Disabled: No one can set two-factor, Required: All users must set two-factor, Optional: Users can set two-factor if they wish.";
  "Feature:TwoFactor.Optional": "Optional";
  "Feature:TwoFactor.Disabled": "Disabled";
  "Feature:TwoFactor.Forced": "Forced";
  "Feature:EnableLdapLogin": "LDAP login";
  "Feature:EnableLdapLoginDescription": "LDAP login";
  "Feature:EnableOAuthLogin": "OAuth login";
  "Feature:EnableOAuthLoginDescription": "OAuth login";
  "DisplayName:Abp.Identity.TwoFactorBehaviour": "Two factor behaviour";
  "Description:Abp.Identity.TwoFactorBehaviour": "Two factor behaviour";
  "DisplayName:Abp.Identity.UsersCanChange": "Allow users to change their Two Factor.";
  "Description:Abp.Identity.UsersCanChange": "Allow users to change their Two Factor.";
  "DisplayName:Abp.Identity.EnableLdapLogin": "Ldap Login";
  "Description:Abp.Identity.EnableLdapLogin": "Enable Ldap login";
  "DisplayName:Abp.Identity.EnableOAuthLogin": "OAuth login";
  "Description:Abp.Identity.EnableOAuthLogin": "Enable OAuth login";
  "DisplayName:Abp.Identity.Authority": "Authority";
  "Description:Abp.Identity.Authority": "Authority";
  "DisplayName:Abp.Identity.ClientId": "Client Id";
  "Description:Abp.Identity.ClientId": "Client Id";
  "DisplayName:Abp.Identity.ClientSecret": "Client secret";
  "Description:Abp.Identity.ClientSecret": "Client secret";
  "DisplayName:Abp.Identity.Scope": "Scope";
  "Description:Abp.Identity.Scope": "Scope";
  "DisplayName:Abp.Identity.RequireHttpsMetadata": "Require Https Metadata";
  "Description:Abp.Identity.RequireHttpsMetadata": "Require Https Metadata";
  "DisplayName:Abp.Identity.ValidateEndpoints": "Validate Endpoints";
  "Description:Abp.Identity.ValidateEndpoints": "Validate Endpoints";
  "DisplayName:Abp.Identity.ValidateIssuerName": "Validate Issuer Name";
  "Description:Abp.Identity.ValidateIssuerName": "Validate Issuer Name";
  "Feature:MaximumUserCount": "Maximum user count";
  "Feature:MaximumUserCountDescription": "Limits the number of users in the public registration and admin user creation screens. For unlimited users enter 0.";
  "Volo.Abp.Identity:010015": "Reached maximum allowed user count! This tenant is allowed to have a maximum of {MaxUserCount} users.";
  LdapPasswordPlaceholder: "Enter to update password";
  LdapLoginSettings: "Ldap Login Settings";
  OAuthLoginSettings: "OAuth Login Settings";
  "Menu:Identity:Ldap": "Ldap Account";
  IdentitySettingsLdap: "Ldap";
  IdentitySettingsOAuth: "OAuth";
  IdentitySettingsGeneral: "General";
  IdentitySettingsSessions: "Sessions";
  "DisplayName:Abp.Identity.PreventConcurrentLogin": "Prevent concurrent login";
  "Description:Abp.Identity.PreventConcurrentLogin": "Allow users to log in simultaneously from any platform or restrict them from having multiple sessions across different clients.";
  "Enum:IdentityProPreventConcurrentLoginBehaviour.Disabled": "Disabled";
  "Enum:IdentityProPreventConcurrentLoginBehaviour.LogoutFromSameTypeDevices": "Logout from same type devices";
  "Enum:IdentityProPreventConcurrentLoginBehaviour.LogoutFromAllDevices": "Logout from all devices";
  "Description:IdentityProPreventConcurrentLoginBehaviour.Disabled": "Users can stay logged in across multiple platforms.";
  "Description:IdentityProPreventConcurrentLoginBehaviour.LogoutFromSameTypeDevices": "Users can keep their sessions active only on different platforms. Only the most recent session is allowed on the same platform. For example, users cannot have 2 different web browser sessions.";
  "Description:IdentityProPreventConcurrentLoginBehaviour.LogoutFromAllDevices": "The system denies concurrent logins; therefore, users can only have 1 active session, which is the most recent one.";
  ClaimValueCanNotBeBlank: "Claim value can not be blank!";
  ClaimValue: "Value";
  Date: "Date";
  ThereIsNoUsersCurrentlyInThisRole: "There is no users currently in this role.";
  UserCount: "User Count";
  ThereIsNoUsersCurrentlyInThisOrganizationUnit: "There is no users currently in this organization unit.";
  ClaimValueIsInvalid: "Claim value '{0}' is invalid.";
  "Permission:ClaimManagement": "Claim management";
  "Permission:ViewChangeHistory": "View change history";
  "Permission:Impersonation": "Impersonation";
  "Permission:SettingManagement": "Setting management";
  "Permission:OrganizationUnitManagement": "Organization unit management";
  "Permission:ManageOU": "Managing organization tree";
  "Permission:ManageUsers": "Managing users";
  "Permission:SecurityLogs": "Security logs";
  "Permission:Import": "Import";
  "Menu:SecurityLogs": "Security logs";
  Lock: "Lock";
  Unlock: "Unlock";
  "UserLockoutNotEnabled{0}": "User '{0}' lockout is not enabled!";
  TwoFactor: "Two factor";
  HideShow: "Hide / Show";
  Name: "Name";
  UserInformation: "User information";
  ClaimTypes: "Claim types";
  "Roles{0}": "Roles ({0})";
  Members: "Members";
  OrganizationUnits: "Organization units";
  "OrganizationUnits{0}": "Org. units ({0})";
  "OrganizationUnit:Parent{0}": "Parent: {0}";
  "OrganizationUnit:Root": "Root unit";
  Type: "Type";
  Claims: "Claims";
  NewClaimType: "New claim type";
  ValueType: "Value type";
  Description: "Description";
  Required: "Required";
  Regex: "Regex";
  RegexDescription: "Regex description";
  RegexDescriptionFormText: "Use localization key";
  IsStatic: "Is Static";
  ClaimTypeDeletionConfirmationMessage: "Are you sure you want to delete the claim type '{0}'?";
  ChooseAnActionForRole: "There are {0} users assigned to the role you are trying to delete. Please choose an action for these users:";
  UnassignTheRoleFromTheUsers: "Unassign the role from the users";
  AssignUsersToOtherRole: "Assign users to another role";
  SelectAnRoleToAssign: "Select a role to assign";
  MoveAllUsers: "Move all users";
  MoveAllUsersWithRoleTo: "Move all users with <b>{0}</b> role to:";
  UnassignRole: "Unassign role";
  OrganizationUnitDeletionConfirmationMessage: "Are you sure you want to delete the organization unit '{0}'?";
  ChooseAnActionForOrganizationUnit: "There are {0} users assigned to the organization unit you are trying to delete. Please choose an action for these users:";
  UnassignTheOrganizationUnitFromTheUsers: "Unassign the organization unit from the users";
  AssignUsersToOtherOrganizationUnit: "Assign users to another organization unit";
  SelectAnOrganizationUnitToAssign: "Select an organization unit to assign";
  MoveAllUsersWithOrganizationUnitTo: "Move all users with <b>{0}</b> organization unit to:";
  UnassignOrganizationUnit: "Unassign organization unit";
  OrganizationUnitMoveSameParentMessage: "Can not move to the same parent!";
  SelectUsers: "Select users";
  SelectRoles: "Select roles";
  "DisplayName:AccessFailedCount": "Access failed count";
  "DisplayName:EmailConfirmed": "Email confirmed";
  "DisplayName:EmailAddress": "Email address";
  "DisplayName:PhoneNumberConfirmed": "Phone number confirmed";
  "DisplayName:ShouldChangePasswordOnNextLogin": "Force password change";
  "Description:ShouldChangePasswordOnNextLogin": "User must change the password at next login";
  UserMustChangePasswordAtNextLogin: "User must change the password at next login";
  "Description:LockoutEnabled": "Lock account after failed login attempts";
  "DisplayName:SendConfirmationEmail": "Send confirmation email";
  SelectAnOrganizationUnitToSeeMembers: "Select an organization unit to see members";
  SelectAnOrganizationUnitToSeeRoles: "Select an organization unit to see roles";
  RemoveUserFromOuWarningMessage: "Are you sure to you want to remove the user {0} from organization unit {1}?";
  RemoveRoleFromOuWarningMessage: "Are you sure to you want to remove the role {0} from organization unit {1}?";
  OrganizationTree: "Organization tree";
  AddRootUnit: "Add root unit";
  AddSubUnit: "Add sub-unit";
  AddRole: "Add role";
  AddMember: "Add member";
  LastModificationTime: "Last modification time";
  GenerateRandomPasswordTooltip: "Generate Random Password";
  PasswordStrengthSettings: "Password strength settings";
  PasswordRenewingSettings: "Password renewing settings";
  SetPassword: "Set password";
  PasswordsAreNotSame: "The given passwords are not equal.";
  UserNotFound: "User is not exist";
  LockoutSettings: "Lockout settings";
  SignInSettings: "Sign in settings";
  PasswordSettings: "Password settings";
  UserSettings: "User settings";
  "DisplayName:LockoutEnd": "Lockout end date";
  ThisUserIsLockedOutMessage: "This user is locked out. To unlock, please click Actions and then Unlock.";
  UserUnlocked: "User unlocked.";
  NotActive: "Not active";
  AddClaim: "Add claim";
  ClaimAlreadyExist: "The claim already exists";
  ChangeHistory: "Change history";
  LoginWithThisUser: "Log in with this user";
  NewOrganizationUnit: "New organization unit";
  DisplayName: "Display name";
  OrganizationUnitMoveConfirmMessage: "Are you sure you want to move '{0}' under '{1}'?";
  NoOrganizationUnits: "No organization units!";
  OrganizationUnitDuplicateDisplayNameWarning: "The organization display name already exists. Please write a different one.";
  SecurityLogs: "Security logs";
  "SecurityLogs:StartTime": "Start time";
  "SecurityLogs:EndTime": "End time";
  "SecurityLogs:Application": "Application";
  "SecurityLogs:ApplicationDescription": "Application name";
  "SecurityLogs:Identity": "Identity";
  "SecurityLogs:IdentityDescription": "Source of the logs. eg: Identity, IdentityExternal, IdentityServer, OpenIddict";
  "SecurityLogs:Action": "Action";
  "SecurityLogs:ActionDescription": "Security action. eg:LoginSucceeded, LoginFailed, Logout";
  "SecurityLogs:UserName": "Username";
  "SecurityLogs:Client": "Client";
  "SecurityLogs:CorrelationId": "Correlation Id";
  "SecurityLogs:Date": "Date";
  "SecurityLogs:IpAddress": "Ip Address";
  "SecurityLogs:Browser": "Browser";
  InvalidLinkToken: "Invalid link token";
  SelectedOrganizationUnit: "Selected organization unit";
  Move: "Move";
  MoveOrganizationUnit: "Move: {0}";
  SeeAdvancedFilters: "Advanced filters";
  Role: "Role";
  OrganizationUnit: "Organization unit";
  UserNameOrEmailAddress: "User name or email address";
  Provider: "Provider";
  NoExternalLoginProviderAvailable: "No external login provider available";
  ExternalUser: "External user";
  "Volo.Abp.Identity:010010": "Invalid external login provider";
  "Volo.Abp.Identity:010011": "External login provider authenticate failed";
  "Volo.Abp.Identity:010012": "Local user already exists";
  Import: "Import";
  True: "True";
  False: "False";
  Tenant: "Tenant";
  CreationStartDate: "Creation start date";
  CreationEndDate: "Creation end date";
  CreationDate: "Creation date";
  ModificationStartDate: "Modification start date";
  ModificationEndDate: "Modification end date";
  ModificationDate: "Modification date";
  EmailConfirmed: "Email confirmed";
  IsExternal: "External";
  External: "External";
  ViewDetails: "View details";
  "Permission:ViewDetails": "View details";
  Dash: "-";
  Export: "Export";
  ToExcel: "To Excel";
  ToCSV: "To CSV";
  UploadFile: "Upload file";
  ChooseFile: "Choose file";
  Upload: "Upload";
  ClickHereToDownloadSampleImportFile: "Click here to download sample import file";
  PleaseSelectFile: "Please Select File";
  DownloadTemplateFile: "Download template file";
  ImportSuccessMessage: "Import completed successfully.";
  ImportFailedMessage: "{1} users failed and {0} successful with the import. Do you want to download non-imported users?";
  "Permission:Export": "Export";
  "Volo.Abp.Identity:010013": "No user found in the file.";
  FromExcel: "From Excel";
  FromCSV: "From CSV";
  Active: "Active";
  PleaseSelectAFile: "Please select a file.";
  "Volo.Abp.Identity:010014": "Invalid import file format.";
  AuthorityDelegation: "Authority delegation";
  DelegateNewUser: "Delegate new user";
  DelegatedUsers: "Delegated users";
  MyDelegatedUsers: "My delegated users";
  DelegationDateRange: "Delegation date range";
  StartTime: "Start time";
  EndTime: "End time";
  Status: "Status";
  StatusActive: "Active";
  StatusExpired: "Expired";
  StatusFuture: "Future";
  "{0}IsStaticRoleCanNotBeRenamed": "{0} role is a static role can not be renamed";
  General: "General";
  "Permission:Sessions": "Sessions";
  Sessions: "Sessions";
  "Session:SessionId": "Session id";
  "Session:Current": "Current session";
  "Session:Device": "Device";
  "Session:DeviceInfo": "Device info";
  "Session:UserInfo": "User info";
  "Session:ClientId": "Client id";
  "Session:IpAddresses": "IP addresses";
  "Session:SignedIn": "Signed in date";
  "Session:LastAccessed": "Last access date";
  "Session:Detail": "Detail";
  "Session:Revoke": "Revoke";
  SessionRevokeConfirmationMessage: "Are you sure you want to revoke the session?";
};
export type AbpLdapResources = {
  "DisplayName:Abp.Ldap.Ldaps": "LDAP over SSL";
  "Description:Abp.Ldap.Ldaps": "LDAP over SSL";
  "DisplayName:Abp.Ldap.ServerHost": "Server host";
  "Description:Abp.Ldap.ServerHost": "Server host";
  "DisplayName:Abp.Ldap.ServerPort": "Server port";
  "Description:Abp.Ldap.ServerPort": "Server port";
  "DisplayName:Abp.Ldap.BaseDc": "Base domain component";
  "Description:Abp.Ldap.BaseDc": "Base domain component";
  "DisplayName:Abp.Ldap.Domain": "Domain";
  "Description:Abp.Ldap.Domain": "Domain";
  "DisplayName:Abp.Ldap.UserName": "Username";
  "Description:Abp.Ldap.UserName": "Username";
  "DisplayName:Abp.Ldap.Password": "Password";
  "Description:Abp.Ldap.Password": "Password";
};
export type AbpOpenIddictResources = {
  TheOpenIDConnectRequestCannotBeRetrieved: "The OpenID Connect request cannot be retrieved.";
  TheUserDetailsCannotBbeRetrieved: "The user details cannot be retrieved.";
  TheApplicationDetailsCannotBeFound: "The application details cannot be found.";
  DetailsConcerningTheCallingClientApplicationCannotBeFound: "Details concerning the calling client application cannot be found.";
  TheSpecifiedGrantTypeIsNotImplemented: "The specified grant type {0} is not implemented.";
  Authorization: "Authorization";
  DoYouWantToGrantAccessToYourData: "Do you want to grant {0} access to your data?";
  ScopesRequested: "Scopes requested";
  Accept: "Accept";
  Deny: "Deny";
  Permissions: "Permissions";
  "Permission:OpenIddictPro": "OpenId";
  "Permission:Edit": "Edit";
  "Permission:Create": "Create";
  "Permission:Delete": "Delete";
  "Permission:Application": "Application";
  "Permission:ManagePermissions": "Manage permissions";
  "Permission:ViewChangeHistory": "View change history";
  ChangeHistory: "Change history";
  "Permission:Scope": "Scope";
  InvalidRedirectUri: "Invalid RedirectUri: {0}";
  InvalidPostLogoutRedirectUri: "Invalid PostLogoutRedirectUri: {0}";
  NoClientSecretCanBeSetForPublicApplications: "No client secret can be set for public applications.";
  TheClientSecretIsRequiredForConfidentialApplications: "The client secret is required for confidential applications.";
  TheClientIdentifierIsAlreadyTakenByAnotherApplication: "The client identifier is already taken by another application.";
  TheScopeNameCannotContainSpaces: "The scope name cannot contain spaces";
  TheNameIsAlreadyTakenByAnotherScope: "The name is already taken by another scope.";
  "Menu:OpenIddict": "OpenId";
  Scopes: "Scopes";
  ScopeDeletionWarningMessage: "Are you sure you want to delete the scope '{0}'?";
  Name: "Name";
  DisplayName: "Display name";
  Description: "Description";
  Resources: "Resources";
  NewScope: "New scope";
  Applications: "Applications";
  ApplicationDeletionWarningMessage: "Are you sure you want to delete the application '{0}'?";
  AreYouSure: "Are you sure?";
  NoAvailableScopes: "There is no available scopes";
  NewApplication: "New application";
  ClientId: "Client Id";
  Type: "Type";
  ClientSecret: "Client secret";
  ClientSecretHelpText: "Enter a new value to replace the existing secret";
  ClientUri: "Client uri";
  LogoUri: "Logo uri";
  AllowAuthorizationCodeFlow: "Allow authorization code flow";
  AllowImplicitFlow: "Allow implicit flow";
  AllowPasswordFlow: "Allow password flow";
  AllowClientCredentialsFlow: "Allow client credentials flow";
  AllowHybridFlow: "Allow hybrid flow";
  AllowRefreshTokenFlow: "Allow refresh token flow";
  AllowDeviceEndpoint: "Allow device endpoint";
  AllowLogoutEndpoint: "Allow logout endpoint";
  ExtensionGrantTypes: "Extension grant types";
  RedirectUris: "Redirect uris";
  PostLogoutRedirectUris: "Post logout redirect uris";
  ConsentType: "Consent type";
  NotAvailableForThisType: "Not available for this type";
  TokenLifetime: "Token Lifetime";
  TokenLifetimeHit: "The unit of token life is seconds, leaving blank to use the default life time.";
  AccessTokenLifetime: "AccessToken lifetime";
  AuthorizationCodeLifetime: "AuthorizationCode lifetime";
  DeviceCodeLifetime: "DeviceCode lifetime";
  IdentityTokenLifetime: "IdentityToken lifetime";
  RefreshTokenLifetime: "RefreshToken lifetime";
  UserCodeLifetime: "UserCode lifetime";
};
export type AbpPermissionManagementResources = {
  Permissions: "Permissions";
  OnlyProviderPermissons: "Only this provider";
  All: "All";
  SelectAllInAllTabs: "Grant all permissions";
  SelectAllInThisTab: "Select all";
  SaveWithoutAnyPermissionsWarningMessage: "Are you sure you want to save without any permissions?";
};
export type AbpSettingManagementResources = {
  Settings: "Settings";
  SavedSuccessfully: "Saved successfully";
  "Permission:SettingManagement": "Setting management";
  "Permission:Emailing": "Emailing";
  "Permission:EmailingTest": "Emailing test";
  "Permission:TimeZone": "Time zone";
  SendTestEmail: "Send test email";
  SenderEmailAddress: "Sender email address";
  TargetEmailAddress: "Target email address";
  Subject: "Subject";
  Body: "Body";
  TestEmailSubject: "Test email {0}";
  TestEmailBody: "Test email body message here";
  SuccessfullySent: "Successfully sent";
  Send: "Send";
  "Menu:Emailing": "Emailing";
  "Menu:TimeZone": "Time Zone";
  "DisplayName:Timezone": "Time zone";
  TimezoneHelpText: "This setting is used for application-wide or tenant-based.";
  SmtpHost: "Host";
  SmtpPort: "Port";
  SmtpUserName: "User name";
  SmtpPassword: "Password";
  SmtpDomain: "Domain";
  SmtpEnableSsl: "Enable ssl";
  SmtpUseDefaultCredentials: "Use default credentials";
  DefaultFromAddress: "Default from address";
  DefaultFromDisplayName: "Default from display name";
  "Feature:SettingManagementGroup": "Setting management";
  "Feature:SettingManagementEnable": "Enable setting management";
  "Feature:SettingManagementEnableDescription": "Enable setting management system in the application.";
  "Feature:AllowChangingEmailSettings": "Allow changing email settings.";
  "Feature:AllowChangingEmailSettingsDescription": "Allow changing email settings.";
};
export type LanguageManagementResources = {
  LanguageManagement: "Language Management";
  Languages: "Languages";
  OnlyEmptyValues: "Only empty values";
  All: "All";
  BaseValue: "Base value";
  LanguageTexts: "Language texts";
  BaseCultureName: "Base culture name";
  BaseCultureValue: "Base culture value";
  TargetCultureValue: "Target culture value";
  TargetCultureName: "Target culture name";
  CultureName: "Culture name";
  UiCultureName: "UI culture name";
  ResourceName: "Resource name";
  RestoreToDefault: "Restore to default";
  SaveAndNext: "Save And Next";
  TargetValue: "Target value";
  Value: "Value";
  Key: "Key";
  Edit: "Edit";
  CreateNewLanguage: "Create new language";
  Delete: "Delete";
  DisplayName: "Display name";
  IsEnabled: "Enabled";
  SetAsDefaultLanguage: "Set as default language";
  DefaultLanguage: "Default language";
  "Menu:Languages": "Language management";
  LanguageDeletionConfirmationMessage: "'{0}' language will be deleted. Do you confirm that?";
  DefaultLanguageDeletionConfirmationMessage: "Default language '{0}' will be deleted. Do you confirm that?";
  Filter: "Filter";
  "Feature:LanguageManagementGroup": "Language management";
  "Feature:LanguageManagementEnable": "Enable language management";
  "Feature:LanguageManagementEnableDescription": "Enable language management system in the application.";
  "Volo.Abp.LanguageManagement:010001": "Culture name {CultureName} already exists.";
  NewLanguageMightRequireRestartInformation: "The web application may need to be restarted for the new language to be fully applied.";
  LanguageDisplayNameInfoText: "if the display name is not specified then the culture name will be used instead";
  "Permission:LanguageManagement": "Language management";
  "Permission:LanguageTexts": "Language texts";
  "Permission:LanguageTextsEdit": "Edit language texts";
  "Permission:Languages": "Languages";
  "Permission:LanguagesEdit": "Edit language";
  "Permission:LanguagesCreate": "Create language";
  "Permission:LanguagesChangeDefault": "Change default language";
  "Permission:LanguagesDelete": "Delete language";
};
export type AbpExceptionHandlingResources = {
  InternalServerErrorMessage: "An internal error occurred during your request!";
  ValidationErrorMessage: "Your request is not valid!";
  ValidationNarrativeErrorMessageTitle: "The following errors were detected during validation.";
  DefaultErrorMessage: "An error has occurred!";
  DefaultErrorMessageDetail: "Error detail not sent by server.";
  DefaultErrorMessage401: "You are not authenticated!";
  DefaultErrorMessage401Detail: "You should sign in to perform this operation.";
  DefaultErrorMessage403: "You are not authorized!";
  DefaultErrorMessage403Detail: "You are not allowed to perform this operation!";
  DefaultErrorMessage404: "Resource not found!";
  DefaultErrorMessage404Detail: "The resource requested could not be found on the server!";
  EntityNotFoundErrorMessage: "There is no entity {0} with id = {1}!";
  AbpDbConcurrencyErrorMessage: "The data you have submitted has already changed by another user/client. Please discard the changes you've done and try from the beginning.";
  Error: "Error";
  UnhandledException: "Unhandled exception!";
  "401Message": "Unauthorized";
  "403Message": "Forbidden";
  "404Message": "Page not found";
  "500Message": "Internal Server Error";
  "403MessageDetail": "You are not authorized to perform this operation!";
  "404MessageDetail": "Sorry, there's nothing at this address.";
};
export type PaymentResources = {
  Delete: "Delete";
  "DisplayName:Code": "Code";
  "DisplayName:CreationTime": "Creation time";
  "DisplayName:Count": "Count";
  "DisplayName:Currency": "Currency";
  "DisplayName:ExternalId": "External Id";
  "DisplayName:FailReason": "Fail Reason";
  "DisplayName:Gateway": "Gateway";
  "DisplayName:Name": "Name";
  "DisplayName:PaymentType": "Payment type";
  "DisplayName:State": "State";
  "DisplayName:TotalPrice": "Total price";
  "DisplayName:UnitPrice": "Unit price";
  "DisplayName:ExternalSubscriptionId": "External Subscription Id";
  Edit: "Edit";
  "Enum:PaymentRequestState:0": "Waiting";
  "Enum:PaymentRequestState:1": "Completed";
  "Enum:PaymentRequestState:2": "Failed";
  "Enum:PaymentRequestState:3": "Refunded";
  GatewayPlanDeletionConfirmationMessage: "The gateway plan will be deleted. Are you sure?";
  GatewayPlans: "Manage gateway plans";
  "Menu:PaymentManagement": "Payment";
  "Menu:PaymentRequests": "Payment requests";
  "Menu:Plans": "Payment plans";
  NewGatewayPlan: "New gateway plan";
  NewPlan: "New plan";
  "Payment:Request:0001": "Can't update existing External Plan Id";
  "PaymentRequests:Search": "Search";
  "PaymentRequests:CreationDateMax": "Fecha de creación máx.";
  "PaymentRequests:CreationDateMin": "Fecha de creación Min";
  "PaymentRequests:PaymentType": "Payment type";
  "PaymentRequests:Status": "Status";
  paypal: "PayPal";
  payu: "PayU";
  PayWithGateway: "Pay with {0}";
  "Permission:Payment": "Payment";
  "Permission:PaymentGatewayPlanManagement": "Payment gateway plan management";
  "Permission:PaymentGatewayPlanManagement.Create": "Create";
  "Permission:PaymentGatewayPlanManagement.Delete": "Delete";
  "Permission:PaymentGatewayPlanManagement.Update": "Update";
  "Permission:PaymentPlanManagement": "Payment plan management";
  "Permission:PaymentPlanManagement.Create": "Create";
  "Permission:PaymentPlanManagement.Delete": "Delete";
  "Permission:PaymentPlanManagement.Update": "Update";
  "Permission:PaymentRequests": "Payment requests";
  PlanDeletionConfirmationMessage: "The plan will be deleted. Are you sure?";
  Plans: "Plans";
  Products: "Products";
  Search: "Search";
  stripe: "Stripe";
  "two-checkout": "2Checkout";
  "Iyzico:NOT_SUFFICIENT_FUNDS": "You have not sufficient funds.";
  "Iyzico:DO_NOT_HONOUR": "Operation not approved.";
  "Iyzico:INVALID_TRANSACTION": "Invalid transaction.";
  "Iyzico:LOST_CARD": "The card has been marked as lost.";
  "Iyzico:STOLEN_CARD": "The card has been marked as stolen.";
  "Iyzico:EXPIRED_CARD": "The card has been expired.";
  "Iyzico:INVALID_CVC2": "Invalid CVC2.";
  "Iyzico:NOT_PERMITTED_TO_CARDHOLDER": "Operation not permitted to card holder.";
  "Iyzico:NOT_PERMITTED_TO_TERMINAL": "Operation not permitted to terminal.";
  "Iyzico:FRAUD_SUSPECT": "A fraud suspect has been identified.";
  "Iyzico:RESTRICTED_BY_LAW": "Your card is closed to e-commerce transactions. Please contact with your bank. ";
  "Iyzico:CARD_NOT_PERMITTED": "The card did not allow the transaction.";
  "Iyzico:UNKNOWN": "An error occurred while processing payment.";
  "Iyzico:INVALID_CVC2_LENGTH": "Invalid CVC2 length";
  "Iyzico:REFER_TO_CARD_ISSUER": "Need to receive approval by bank.";
  "Iyzico:INVALID_MERCHANT_OR_SP": "Invalid bank merchant category";
  "Iyzico:BLOCKED_CARD": "The card has been identified as blocked.";
  "Iyzico:INVALID_CAVV": "Invalid CAVV.";
  "Iyzico:INVALID_ECI": "Invalid ECI.";
  "Iyzico:BIN_NOT_FOUND": "Bin is not found.";
  "Iyzico:COMMUNICATION_OR_SYSTEM_ERROR": "Communication or system error has been occured.";
  "Iyzico:INVALID_CARD_NUMBER": "The card number is invalid.";
  "Iyzico:NO_SUCH_ISSUER": "Issuer could not found for the card.";
  "Iyzico:DEBIT_CARDS_REQUIRES_3DS": "Debit cards require 3D-Secure.";
  "Iyzico:REQUEST_TIMEOUT": "Request timeout.";
  "Iyzico:NOT_PERMITTED_TO_INSTALLMENT": "Installment option not allowed for the terminal.";
  "Iyzico:REQUIRES_DAY_END": "Requires day end";
  "Iyzico:RESTRICTED_CARD": "The card has been identified as restricted.";
  "Iyzico:EXCEEDS_ALLOWABLE_PIN_TRIES": "Max PIN tries exceeded.";
  "Iyzico:INVALID_PIN": "Invalid PIN.";
  "Iyzico:ISSUER_OR_SWITCH_INOPERATIVE": "Bank or terminal is not processing the operation.";
  "Iyzico:INVALID_EXPIRE_YEAR_MONTH": "Expiration year or month is invalid.";
  "Iyzico:INVALID_AMOUNT": "Invalid amount";
  "Iyzico:REFUND_NOT_ALLOWED_FOR_THIS_DEBIT_CARD": "There is not enough balance on the card. ";
  "Iyzico:APPROVED_COMPLETED": "This transaction has been already approved. ";
  "Iyzico:INVALID_CHARS_IN_EMAIL": "Email is not in valid format.";
  "Iyzico:CVC2_MAX_ATTEMPT": "Max CVC2 tries exceeded.";
  "Iyzico:DEBIT_CARDS_INSTALLMENT_NOT_ALLOWED": "Installments not allowed with debit cards. ";
  "Iyzico:DECLINED": "Payment not received.";
  "Iyzico:NOT_PERMITTED_TO_FOREIGN_CARD": "Terminal is closed to foreign/international cards.";
  "Iyzico:EXCEEDS_WITHDRAWAL_AMOUNT_LIMIT": "Withdrawal limit exceeded.";
  "Iyzico:REQUEST_BLOCKED_BY_BANK": "The request has been blocked by bank.";
  "Iyzico:SALES_AMOUNT_LESS_THAN_AWARD": "The sales amount cannot be lower than the award points.";
  "Iyzico:INVALID_CARD_TYPE": "Invalid card type.";
  "Iyzico:NOT_SUFFICIENT_AWARD": "Insufficient award points.";
  "Iyzico:AMEX_CAN_USE_ONLY_MR": "American Express (AMEX) card error.";
  PriceSubscriptionTooltip: "Subscription pricing is managed by payment gateway.";
  "PaymentType:OneTime": "One time";
  "PaymentType:Subscription": "Subscription";
};
export type SaasResources = {
  "Volo.Saas:DuplicateTenantName": "Tenant name already exists: {Name}";
  "Volo.Saas:DuplicateEditionDisplayName": "Edition display name already exists: {Name}";
  "Menu:Saas": "Saas";
  Tenants: "Tenants";
  NewTenant: "New tenant";
  EditTenant: "Edit tenant";
  TenantBaseInfo: "Base info";
  TenantName: "Tenant name";
  "DisplayName:TenantName": "Tenant name";
  TenantCount: "Tenant count";
  TenantDeletionConfirmationMessage: "Tenant '{0}' will be deleted. Do you confirm that?";
  EditionDeletionConfirmationMessage: "Edition '{0}' will be deleted. Do you confirm that?";
  ChooseAnAction: "There are {0} tenants assigned to the edition you are trying to delete. Please choose an action for these tenants:";
  UnassignTheEditionFromTheTenants: "Unassign the edition from the tenants";
  AssignTenantsToOtherEdition: "Assign tenants to other edition";
  SelectAnEditionToAssign: "Select an edition to assign";
  MoveAllTenants: "Move all tenants";
  ThereIsNoTenantsCurrentlyInThisEdition: "This edition has no tenants.";
  MoveAllTenantsWithEditionTo: "Move all tenants with <b>{0}</b> edition to:";
  UnassignEdition: "Unassign edition";
  ConnectionStrings: "Database connection strings";
  AddDatabaseConnectionString: "Add";
  "DisplayName:Default": "Default connection string";
  "DisplayName:DatabaseName": "Module";
  "DisplayName:ConnectionString": "Database connection string";
  "DisplayName:UseSharedDatabase": "Use the shared database";
  "DisplayName:UseSpecificDatabase": "Use module specific database connection string";
  "DisplayName:EditionId": "Edition";
  Edition: "Edition";
  Editions: "Editions";
  EditionEndDateUtc: "Edition expiration date (UTC)";
  NewEdition: "New edition";
  EditionName: "Edition name";
  Name: "Name";
  LatestTenants: "Latest tenants";
  EditionUsageStatistics: "Edition usage statistics";
  "DisplayName:AdminEmailAddress": "Tenant admin's email address";
  "DisplayName:AdminEmailAddressFormText": "Tenant's email cannot be changed after creation";
  "DisplayName:AdminPassword": "Tenant admin's password";
  "DisplayName:ActivationState": "Tenant activation state";
  "DisplayName:ActivationEndDate": "Tenant activation end date";
  "DisplayName:ExpirationDate": "Edition expiration date";
  ActivationState: "Activation state";
  "Enum:TenantActivationState.Active": "Active";
  "Enum:TenantActivationState.ActiveWithLimitedTime": "Active with limited time";
  "Enum:TenantActivationState.Passive": "Passive";
  ChangeHistory: "Change history";
  SetPassword: "Set password";
  LoginWithThisTenant: "Login with this tenant";
  ApplyDatabaseMigrations: "Apply database migrations";
  DatabaseMigrationQueuedAndWillBeApplied: "Database migration has been queued and will be applied soon.";
  "Saas:Edition:0001": "Edition doesn't have a plan!";
  "Saas:Edition:0002": "Unable to delete {EditionName}, It is in use by tenants.";
  PlanId: "Plan";
  PlanName: "Plan";
  SeeAdvancedFilters: "Advanced filters";
  ValidConnectionString: "The connection string is valid";
  InvalidConnectionString: "The connection string is not valid";
  CheckConnectionString: "Test";
  NoDataAvailable: "No data available";
  GenerateRandomPasswordTooltip: "Generate a random password or use your own";
  Password: "Password";
  UserName: "User name";
  UserNameTooltip: "Enter the user name you want to change for the tenant";
  GeneratePassword: "Generate password";
  EditionEndDateToolTip: "This date is managed by the external payment provider. It will be set automatically after payment and will be updated after each recurring payment.";
  Dash: "-";
  "Permission:Saas": "Saas";
  "Permission:TenantManagement": "Tenant management";
  "Permission:EditionManagement": "Edition management";
  "Permission:Create": "Create";
  "Permission:Edit": "Edit";
  "Permission:Delete": "Delete";
  "Permission:ManageConnectionStrings": "Manage connection strings";
  "Permission:SetPassword": "Set password";
  "Permission:ManageFeatures": "Manage features";
  "Permission:ViewChangeHistory": "View change history";
  "Permission:Impersonation": "Impersonation";
  CheckYourProviderDashboard: "Check your payment provider's dashboard to cancel this subscription.";
};
export type TextTemplateManagementResources = {
  "Menu:TextTemplates": "Text templates";
  "Menu:TextTemplates:TemplateDefinitions": "Template definitions";
  "Permission:TextTemplateManagement": "Text template management";
  "Permission:TextTemplates": "Text templates";
  "Permission:EditContents": "Edit contents";
  TemplateContents: "Template contents";
  Name: "Name";
  Layout: "Layout";
  IsLayout: "Is Layout";
  LocalizationResource: "Localization resource";
  DefaultCultureName: "Default culture name";
  Contents: "Contents";
  SeeContents: "See contents";
  EditContents: "Edit contents";
  BaseCultureName: "Reference culture name";
  TargetCultureName: "Target culture name";
  BaseContent: "Reference content";
  TargetContent: "Target content";
  SaveContent: "Save content";
  RestoreToDefault: "Restore to default";
  RestoreToDefaultMessage: "Are you sure? This action will convert the content to the default value.";
  IsInlineLocalized: "Inline localized";
  Success: "Success";
  TemplateContentUpdated: "Template content updated successfully.";
  TemplateContentRestoredToDefault: "Template content restored to the default value.";
  TemplateContent: "Template content";
  InlineContentDescription: 'This template uses inline localization. You can use the <b>L</b> function to localize a text, like <b>{{L "Hello"}}</b>. If you still want to define a completely new template for a culture, use the "Customize per culture" button. <br /> To get more information about syntax and other details, please check the <a href="https://docs.abp.io/en/abp/latest/Text-Templating" target="_blank">Text Templates documentation</a>.';
  CustomizePerCulture: "Customize per culture";
  DisplayName: "Display name";
  Search: "Search";
  ReturnToTemplates: "Return to templates";
  "Feature:TextManagementGroup": "Text template management";
  "Feature:TextManagementEnable": "Enable text template management";
  "Feature:TextManagementEnableDescription": "Enable text management system in the application.";
};
export type AbpGdprResources = {
  "Volo.Abp.Gdpr:010001": "You have previously requested to download personal data. Once the given request time period has passed, you can create a new one.";
  "Volo.Abp.Gdpr:010002": "Your personal data is still being prepared. You can download it at {GdprDataReadyTime}.";
  PersonalData: "Personal Data";
  "Menu:PersonalData": "Personal data";
  PersonalDataDescription: "Your account contains the personal data that you have given us. This page allows you to download or delete that data.";
  RequestPersonalData: "Request Personal Data";
  DeletePersonalData: "Delete Personal Data";
  CreationTime: "Creation Time";
  Action: "Action";
  Preparing: "Preparing";
  Download: "Download";
  ReadyTime: "Ready Time";
  DeletePersonalDataWarning: "Deleting this data will remove your account and you will no longer log in to the application! Are you sure you want to proceed?";
  PersonalDataDeleteRequestReceived: "Your personal data delete request is being processed... At the end of the data deletion process, your account will be deleted and you will no longer be able to use it.";
  PersonalDataPrepareRequestReceived: "Your personal data request is being processed. You can download it from this page, once it's ready!";
  NoDataAvailable: "No data is available.";
  Accept: "Accept";
  CookiePolicy: "Cookie Policy";
  PrivacyPolicy: "Privacy Policy";
  ThisWebsiteUsesCookie: "This website uses cookies to ensure you get the best experience on the website.";
  CookieConsentAgreePolicies: "If you continue to browse, then you agree to our {0} and {1}.";
  CookieConsentAgreePolicy: "If you continue to browse, then you agree to our {0}.";
  CanNotGetDownloadToken: "You can't get a download token for this request!";
};
export type AbpGlobalFeatureResources = {
  "Volo.GlobalFeature:010001": "The '{ServiceName}' service needs to enable '{GlobalFeatureName}' feature.";
};
export type BlobStoringDatabaseResources = {
  MyAccount: "My account";
};
export type UpwithCrowdResources = {
  "Menu:Home": "Home";
  "Menu:ContactUs": "Contact Us";
  "Menu:ArticleSample": "Article Sample";
  Home: "Home";
  Welcome: "Welcome";
  LongWelcomeMessage: "Welcome to the application. This is a startup project based on the ABP framework. For more information visit";
  Date: "Date";
  "Permission:Dashboard": "Dashboard";
  "Menu:Dashboard": "Dashboard";
  "Menu:HomePage": "Home page";
  Dashboard: "Dashboard";
  "ExternalProvider:Google": "Google";
  "ExternalProvider:Google:ClientId": "Client ID";
  "ExternalProvider:Google:ClientSecret": "Client secret";
  "ExternalProvider:Microsoft": "Microsoft";
  "ExternalProvider:Microsoft:ClientId": "Client ID";
  "ExternalProvider:Microsoft:ClientSecret": "Client secret";
  "ExternalProvider:Twitter": "Twitter";
  "ExternalProvider:Twitter:ConsumerKey": "Consumer key";
  "ExternalProvider:Twitter:ConsumerSecret": "Consumer secret";
  NewsletterHeader: "Subscribe to the newsletter!";
  NewsletterInfo: "Get information about the latest happenings.";
  NewsletterPreference_Default: "Default newsletter";
  NewsletterPrivacyAcceptMessage: "I accept the <a href='/privacy-policy'>Privacy Policy</a>.";
  Language: "Language";
  Search: "Search";
  LoadMore: "Load more";
  Settings: "Settings";
  Theme: "Theme";
  DeviceTheme: "Device theme";
  Dark: "Dark";
  Light: "Light";
  Unspecified: "System";
  SeeAllUsers: "See all Users";
  TakePhoto: "Take photo";
  ChoosePhoto: "Choose pshoto";
  "Permission:Members": "Members";
  "Permission:Members.Save": "Saving the Members";
  "Permission:Members.Delete": "Delete the Members";
  "Permission:Members.Update": "Update the Members";
  "Permission:Members.List": "List the Members";
  "Permission:Members.All": "All Members";
  "Permission:Members.Switch": "Switch the Members";
  "Permission:Projects": "Projects";
  "Permission:Projects.Save": "Saving the Projects";
  "Permission:Projects.Update": "Update the Projects";
  "Permission:Projects.Delete": "Delete the Projects";
  "Permission:Projects.GetTotalBalance": "Total Balance Inquiry Information";
  "Permission:Projects.ProjectLimitQuery": "Project Limit Query";
  "Permission:Projects.List": "List the Projects";
  "Permission:Projects.All": "All Project";
  "Permission:Projects.FundingUpdate": "Funding Update the ProjectPermission";
  "Permission:Projects.FundingDetail": "Funding Detail the ProjectPermission";
  "Permission:Projects.Detail": "Detail the ProjectPermission";
  "Permission:Payments": "Payments";
  "Permission:Payments.Save": "Saving the Payment Transaction";
  "Permission:Payments.List": "List the Payment Transaction";
  "Permission:Payments.All": "All Payment Transaction";
  "Permission:ProjectEntrepreneur": "ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.Save": "Saving the ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.Update": "Update the ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.Delete": "Delete the ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.List": "List the ProjectEntrepreneur";
  "Permission:CustomPermissions": "CustomPermissions";
  "Permission:CustomPermissions.Save": "Saving the CustomPermissions";
  "Permission:CustomPermissions.Update": "Update the CustomPermissions";
  "Permission:CustomPermissions.Delete": "Delete the CustomPermissions";
  "Permission:CustomPermissions.List": "List the CustomPermissions";
  "Permission:CustomRoles": "CustomRoles";
  "Permission:CustomRoles.Save": "Saving the CustomRoles";
  "Permission:CustomRoles.Update": "Update the CustomRoles";
  "Permission:CustomRoles.Delete": "Delete the CustomRoles";
  "Permission:CustomRoles.List": "List the CustomRoles";
  "Permission:ProjectPermission": "ProjectPermission";
  "Permission:ProjectPermission.Save": "Saving the ProjectPermission";
  "Permission:ProjectPermission.Update": "Update the ProjectPermission";
  "Permission:ProjectPermission.Delete": "Delete the ProjectPermission";
  "Permission:ProjectPermission.List": "List the ProjectPermission";
  "Permission:UserMembers": "UserMembers";
  "Permission:UserMembers.Save": "Saving the UserMembers";
  "Permission:UserMembers.Delete": "Delete the UserMembers";
  "Permission:UserMembers.Update": "Update the UserMembers";
  "Permission:UserMembers.List": "List the UserMembers";
  "Permission:UserMembers.All": "All UserMembers";
  "Permission:Tasks": "Task";
  "Permission:Tasks.Save": "Saving the Task";
  "Permission:Tasks.Delete": "Delete the Task";
  "Permission:Tasks.Update": "Update the Task";
  "Permission:Tasks.List": "List the Task";
  "Permission:Tasks.All": "All Task";
  "Permission:Sections": "Sections";
  "Permission:Sections.Save": "Saving the Section and Project";
  "Permission:Sections.Delete": "Delete the Section and Project";
  "Permission:Sections.Update": "Update the Section and Project";
  "Permission:Sections.List": "List the Section and Project";
  "Permission:Sections.All": "All Section and Project";
  "Permission:MimeType": "MimeTypes";
  "Permission:MimeType.Save": "Saving the MimeTypes";
  "Permission:MimeType.Delete": "Delete the MimeTypes";
  "Permission:MimeType.Update": "Update the MimeTypes";
  "Permission:MimeType.List": "List the MimeTypes";
  "Permission:FileTypeGroup": "FileTypeGroup";
  "Permission:FileTypeGroup.Save": "Saving the FileTypeGroup";
  "Permission:FileTypeGroup.Delete": "Delete the FileTypeGroup";
  "Permission:FileTypeGroup.Update": "Update the FileTypeGroup";
  "Permission:FileTypeGroup.List": "List the FileTypeGroup";
  "Permission:File": "File";
  "Permission:File.Save": "Saving the File";
  "Permission:File.Delete": "Delete the File";
  "Permission:File.Update": "Update the File";
  "Permission:File.List": "List the File";
  "Permission:FileType": "FileType";
  "Permission:FileType.Save": "Saving the FileType";
  "Permission:FileType.Delete": "Delete the FileType";
  "Permission:FileType.Update": "Update the FileType";
  "Permission:FileType.List": "List the FileType";
  "Permission:Providers": "Providers";
  "Permission:Providers.Save": "Saving the Providers";
  "Permission:Providers.Delete": "Delete the Providers";
  "Permission:Providers.Update": "Update the Providers";
  "Permission:Providers.List": "List the Providers";
  "Permission:FileRelated": "FileRelated";
  "Permission:FileRelated.Save": "Saving the FileRelated";
  "Permission:FileRelated.Delete": "Delete the FileRelated";
  "Permission:FileRelated.Update": "Update the FileRelated";
  "Permission:FileRelated.List": "List the FileRelated";
  "Permission:Category": "Category";
  "Permission:Category.Save": "Saving the Category";
  "Permission:Category.Delete": "Delete the Category";
  "Permission:Category.Update": "Update the Category";
  "Permission:Category.List": "List the Category";
  "Permission:Type": "Type";
  "Permission:Type.Save": "Saving the Type";
  "Permission:Type.Delete": "Delete the Type";
  "Permission:Type.Update": "Update the Type";
  "Permission:Type.List": "List the Type";
  "Permission:FileTypeMimeType": "FileTypeMimeType";
  "Permission:FileTypeMimeType.Save": "Saving the FileTypeMimeType";
  "Permission:FileTypeMimeType.Delete": "Delete the FileTypeMimeType";
  "Permission:FileTypeMimeType.Update": "Update the FileTypeMimeType";
  "Permission:FileTypeMimeType.List": "List the FileTypeMimeType";
  "UpwithCrowd:CustomRoles:BoardMember": "Board Member";
  "UpwithCrowd:CustomRoles:Co-Founder": "Co-Founder";
  "UpwithCrowd:CustomRoles:TeamMember": "Team Member";
  "UpwithCrowd:Sectors:A": "WOODWORKING";
  "UpwithCrowd:Sectors:B": "ENTERTAINMENT, RECREATION, ORGANIZATION";
  "UpwithCrowd:Sectors:C": "ELECTRIC, ELECTRONICS, COMPUTER";
  "UpwithCrowd:Sectors:D": "FOOD, AGRICULTURE";
  "UpwithCrowd:Sectors:E": "CLOTHING, LEATHER PRODUCTS, HOME TEXTILES, WEAVING";
  "UpwithCrowd:Sectors:F": "GIFTWARE, EDUCATION, PRINTING, PHOTOGRAPHY, VARIOUS GOODS";
  "UpwithCrowd:Sectors:G": "HAIRDRESSER, BARBER, CLEANING, SPORTS, COSMETICS, HEALTH";
  "UpwithCrowd:Sectors:H": "METAL, AUTOMOTIVE, MACHINERY";
  "UpwithCrowd:Sectors:I": "MARKET, MOBILE";
  "UpwithCrowd:Sectors:J": "TRANSPORTATION SERVICES";
  "UpwithCrowd:Sectors:K": "BUILDING ARTS";
  "00000": "Operation Successful";
  EM000: "Message format error";
  EM001: "Message type is not valid.";
  EM003: "You do not have authorization for the address you want to access.";
  EM004: "An unexpected error occurred while processing the message.";
  EM005: "Sender message reference must be unique per platform.";
  EM006: "Welding error";
  EM007: "A request was attempted with an unsupported file ID. The expected value is application/json.";
  "UpwithCrowd:EM008": "Please try again with a valid JSON.";
  EM009: "Could not find the basic message information to create a message.";
  EM013: "The operation could not be completed due to high volume, please try again.";
  EM014: "An error occurred during the data insertion/update operation because uniqueness could not be ensured. The record you are trying to insert already exists. Please check.";
  "UpwithCrowd:EM016": "VKN kimlik tipi ile yalnızca unvan bilgisi iletilmelidir.İsim ve soyisim bilgisi iletilmemelidir.";
  "UpwithCrowd:EM017": "Only name and surname information should be transmitted with the TR ID/YKN/MKN identity type. Title information should not be transmitted.";
  "UpwithCrowd:EM018": "Enter a valid value for the identity number. This value must be 11 for TR ID/YKN, 10 or 11 for VKN, 11 for MKN, and 8 for Registry.";
  EM024: "The message type in the message content is incompatible with the service.";
  EM031: "No record found for the transmitted ID number and request ID.";
  EM032: "The transmitted ID number and request ID verification result failed.";
  EM040: "The KFS system is temporarily unavailable.";
  EM041: "The license you use to access KFS has expired. Please contact the authorized person.";
  EM042: "The platform code that sent the message does not match the platform code in the message.";
  EM044: "An unexpected error occurred while verifying your license.";
  EM045: "The escrow officer that sent the message does not match the platform code in the message.";
  EM046: "The licensed platform could not be found in the system.";
  EM047: "The license information is invalid.{0}";
  EM048: "The Authorization (License) value could not be found in the header.{0}.";
  EPL01: "Platform kodu geçerli değildir.";
  EPL02: "Fund Collection Type should be Share only.";
  "UpwithCrowd:EPL03": "There is an active member record for the ID sent on the relevant platform.";
  EPL04: "There is no active member record for the ID sent on the relevant platform.";
  "UpwithCrowd:EEN01": "Entrepreneur information is not valid. ID could not be found or ID / Name Surname / Title does not match.";
  "UpwithCrowd:EEN02": "Only one Lead participant should be sent in the Entrepreneur information set.";
  "UpwithCrowd:EEN03": "There should be at least one Lead participant in the Entrepreneur information set.";
  "UpwithCrowd:EEN04": "There cannot be more than one record with the same Entrepreneur information in the Entrepreneur information set.";
  "UpwithCrowd:EPR01": "Project code is not valid. No active Project could be found for the relevant Platform.";
  "UpwithCrowd:EPR02": "Only $UPDATABLE_PROJECT_FIELDS fields can be updated.";
  EPR03: "The relevant Entrepreneur/Entrepreneurship Company has created a new cannot start a project.";
  EPR04: "The amount of funds collected is not sufficient for the project to be put on hold or successfully completed. Please check";
  EPR05: "The qualification rate is not sufficient for the project to be put on hold or successfully completed. Please check.";
  EPR06: 'The issuance limit upper amount in the last "$PROJECTS_CONTROL_DURATION" month is exceeded, the relevant entrepreneur/startup company cannot start a new project during this period';
  EPR07: "The fundable amount including additional funds has been exceeded. Please check.";
  EPR08: "The project status has been updated as successful, the project cannot be updated again.";
  EPR09: "The current project limit could not be reached.";
  EPR10: "There is an active project with the same name on the relevant platform.";
  EPR11: "Entrepreneur information set could not be found";
  EPR12: "The project status must be 'Successful' in order to enter the company status";
  EPR13: "The qualified rate must be entered as at least 10% for projects over 1,000,000";
  EPR14: "The relevant entrepreneur/enterprise company cannot start a new debt-based project during this period";
  EPR15: 'The issuance limit upper amount in the last "$PROJECTS_CONTROL_DURATION_DBIT" month is exceeded, the relevant entrepreneur/enterprise company cannot start a new debt-based project during this period.';
  EPR18: "For projects with debt type information, no campaigns more than 50% of the discounted value of the cash flows and credit report can be defined.";
  EPR19: "The transmitted Masterreferance information could not be found in the system";
  EPR20: "No other project of the same project type can be started with MasterReference / MasterReference has been used before.";
  EPR22: "The project you want to produce with MASTERREFERANCE must be active.";
  EPR23: "Projects in failed or canceled status cannot be updated as active, waiting or successful.";
  EPR24: "The project you want to produce with MASTERREFERANCE does not have platform compatibility.";
  EPR25: "You have an active project with the same masterreference. The relevant project cannot be updated as successful.";
  EPR26: "You have an unsuccessful/cancelled project with the same masterreference. The relevant project cannot be updated as successful/waiting.";
  EPR27: "The MASTERREFERANCE does not match the lead entrepreneur id information of the project you want to produce.";
  "UpwithCrowd:EMB01": 'The member information is not valid. ID could not be found or ID / Name Surname / Title does not match. (For legal entities, the title information compatible with the Ministry of Finance will be added to the error message as "UNVAN/..".)';
  EMB02: "No valid registry record could be found in MKS with the transmitted registry information.";
  "UpwithCrowd:EMB03": 'Only "$UPDATABLE_MEMBER_FIELDS" fields can be updated. (The fields to be updated will be taken from the UPDATABLE_MEMBER_FIELDS parameter.)';
  EMB04: "No active record of the member could be found on the transmitted platform.";
  EMB05: "The member to be deleted has an active funding request. Please check.";
  "UpwithCrowd:EMB06": "Name and surname or title information should be provided for the registration identity type.";
  EMB07: "Please notify with TR ID/YKN/MKN for this member.";
  ELM01: "The project's open limit is not suitable.";
  ELM03: "The member's open limit is not suitable.";
  ELM04: "No active limit reduction (funding) message could be found for the reference sent in the message on the relevant platform.";
  ELM05: "An unexpected error occurred during member limit update.";
  ELM06: "An unexpected error occurred during project limit update";
  ELM07: "Limit reduction date must be greater than the project start date.";
  ELM08: "A limit increase message has been previously sent for the relevant limit reduction message.";
  ELM09: "For the relevant limit reduction message the amount of partial limit increase transmitted exceeds the total amount.";
  ELM10: "The member's open borrowing limit is not suitable.";
  ELM11: "The member's maximum borrowing amount for this project is not suitable.";
  EPL08: "The platform must perform a transaction based on borrowing for the entrepreneur risk query.";
  EEN10: "There is no record in the YRTS system as of the query date for the ID you transmitted.";
  EM050: "An error was received from the YRTS system";
  ERO03: "The project to which the rights owner is forwarded must have been successfully completed.";
  ERO01: "There is a list of rights owners notified for the same project. To forward a new list, please cancel the relevant notification first.";
  ERO04: "The type of the project forwarded is not compatible with the type information in the content. (DBIT/SHRE)";
  ERO02: "The rights usage notification to be canceled could not be found";
  ECSV1: "CSV field format error. Field: $element.errorColumn";
  ECSV2: "There cannot be more than one row with the same sequence number.";
  ECSV3: "There cannot be more than one row with the same content.";
  ECSV4: "The number of rows cannot be greater than $max_right_owner_csv_count. You can forward the remaining message in a separate part";
  RPR01: "The report type is not valid";
  RPR02: "With the relevant query criterion The transmitted report is empty";
  RPR03: "The report creation date cannot be greater than the current date.";
  RPR04: "The report creation date cannot be {$maxreportrange} before the current date";
  RPR05: "You have an active report link. Please try again after you have completed downloading your active report";
  RPR06: "You have reached the daily maximum number for this report, please try again";
  RPR07: "You can create a report with a maximum of '$.MAX_REPORT_ROWS' rows";
  RPR08: "The link you want to download is not valid / the link is not platform compatible";
  RPR09: "The link you want to download is in preparation. Please try again later";
  RPR10: "The link has been used before or is inactive. Please create a new link";
  RPR11: "Currently busy, please try again later";
  RPR12: "Project id information is entered only for the transaction type report type";
  FLG01: "No action can be taken on the project. Please contact the MKK authorities.";
  EPR28: "The project must be active or successful (for the balance information service)";
  EPR29: "The start date cannot be updated to a later date due to project limits.";
  "UpwithCrowd:EPR30": "Please enter a valid Identity Type value.";
  "UpwithCrowd:EPR31": "The current user ID could not be accessed because it is null.";
  "UpwithCrowd:EPR32": "No records matching the specified criteria were found.";
  "UpwithCrowd:EPR33": "Member not found.";
  "UpwithCrowd:EPR34": "A project with this name is available on the platform.";
  "UpwithCrowd:EPR35": "There is an active project record for the Project ID sent on the relevant platform.";
  "UpwithCrowd:EPR36": "You do not have authorization for the user you want to update.";
  "UpwithCrowd:EPR37": "Please enter a valid type value.";
  "UpwithCrowd:EPR38": "You do not have permissions for the project you want to update.";
  "UpwithCrowd:EPR39": "The RelatedTransactionID value cannot be null or empty. The operation could not be completed.";
  "UpwithCrowd:EPR40": "Entrepreuner with ID '{id}' was not found.";
  "UpwithCrowd:EPR41": "Duplicate record found for PermissionName '{permissionName}' and PermissionType '{permissionType}'.";
  "UpwithCrowd:EPR42": "Duplicate record found for RolesName '{rolesName}' and RolesType '{rolesType}'.";
  "UpwithCrowd:EPR43": "The Custom Permission with ID {CustomPermissionId} does not exist.";
  "UpwithCrowd:EPR44": "The Custom Role with ID {CustomRoleId} does not exist.";
  "UpwithCrowd:EPR45": "The specified permission already exists and is active.";
  "UpwithCrowd:EPR46": "This member has already been assigned to the project with this role.";
  "UpwithCrowd:EPR47": "Custom role  not found: {name} of type {customRoleType}.";
  "UpwithCrowd:EPR48": "Authorization error: The user does not have manager permission for this project.";
  "UpwithCrowd:EPR49": "Authorization error: The user does not have the required permission for this project.";
  "UpwithCrowd:EPR50": "You are not authorized to delete this member.";
  "UpwithCrowd:EPR51": "You do not have permission to delete this project.";
  "UpwithCrowd:EPR52": "input cannot be null";
  "UpwithCrowd:EPR53": "A member with the same MemberId is already associated.";
  "UpwithCrowd:EPR54": "Only one individual member can be associated with the user.";
  "UpwithCrowd:EPR55": "The member type must be either 'Organization' or 'Individual'.";
  "UpwithCrowd:EPR56": "E-State verification has not been completed. Please complete the verification process.";
  "UpwithCrowd:EPR57": "Your authorization for the payment process is insufficient. Please check your membership permissions or contact the support team.";
  "UpwithCrowd:EPR58": "Cancellation and refund rights cannot be exercised before payment is confirmed.";
  "UpwithCrowd:EPR59": "The right of withdrawal cannot be exercised after the payment has been confirmed. This can only be done before confirmation.";
  "UpwithCrowd:EPR60": "A DecreaseType value must be specified for the return process. Please select an appropriate type.";
  "UpwithCrowd:EPR61": "No payment was found with the specified RelatedTransactionID. Please provide a valid transaction ID.";
  "UpwithCrowd:EPR62": "The payment transaction has already been rejected by TakasBank.";
  "UpwithCrowd:EPR63": "Duplicate record found.";
  "UpwithCrowd:EPR64": "The file content does not match the specified MIME type. Please ensure the file is in the correct format.";
  "UpwithCrowd:EPR65": "The FundNominal value cannot be greater than the Fundable Amount. Please enter a valid value.";
  "UpwithCrowd:EPR66": "Error: FileType could not be found for the namespace {namespaceName}. Please make sure you have entered a valid namespace.";
  "UpwithCrowd:EPR67": "Error: FileTypeGroup could not be found for the namespace {namespaceName}. Please make sure you have entered a valid namespace.";
  "UpwithCrowd:EPR72": "Error: RelatedEntity could not be found for the relatedEntityName {relatedEntityName}. Please make sure you have entered a valid relatedEntityName.";
  "UpwithCrowd:EPR68": "'FileType' and 'FileTypeGrup' namespaces cannot be empty at the same time. Please make sure at least one of them is provided.";
  "UpwithCrowd:EPR69": "You do not have permission to perform this action.";
  "UpwithCrowd:EPR70": "You can only upload one file for this file type. Please select only one file and try again.";
  "UpwithCrowd:EPR71": "The refund amount you requested cannot exceed the deposited amount.";
  "UpwithCrowd:EPR73": "If the isMulti field is true, the maxFileCount value cannot be null.";
};
export type AbpDddApplicationContractsResources = {
  MaxResultCountExceededExceptionMessage: "{0} can not be more than {1}! Increase {2}.{3} on the server side to allow more results.";
};
export type AbpAuthorizationResources = {
  "Volo.Authorization:010001": "Authorization failed! Given policy has not granted.";
  "Volo.Authorization:010002": "Authorization failed! Given policy has not granted: {PolicyName}";
  "Volo.Authorization:010003": "Authorization failed! Given policy has not granted for given resource: {ResourceName}";
  "Volo.Authorization:010004": "Authorization failed! Given requirement has not granted for given resource: {ResourceName}";
  "Volo.Authorization:010005": "Authorization failed! Given requirements has not granted for given resource: {ResourceName}";
};
export type AbpAccountResources = {
  "Volo.Account:InvalidEmailAddress": "Can not find the given email address:{0}";
  "Volo.Account:SelfRegistrationDisabled": "Self registration is disabled!";
  "Volo.Account:PhoneNumberEmpty": "Phone number is empty!";
  "Volo.Account:PhoneNumberConfirmationDisabled": "Phone number confirmation is disabled!";
  "Volo.Account:InvalidUserToken": "Invalid user token!";
  "Volo.Account:UnsupportedTwoFactorProvider": "Unsupported Two factor provider!";
  "Volo.Account:ImpersonateTenantOnlyAvailableForHost": "Impersonate tenant only available for host!";
  "Volo.Account:RequirePermissionToImpersonateTenant": "Require {PermissionName} permission to impersonate tenant!";
  "Volo.Account:ThereIsNoUserWithUserName": "There is no user with username: {UserName}!";
  "Volo.Account:YouCanNotImpersonateYourself": "You can't impersonate yourself!";
  "Volo.Account:NestedImpersonationIsNotAllowed": "Nested impersonation is not allowed!";
  "Volo.Account:RequirePermissionToImpersonateUser": "Require {PermissionName} permission to impersonate user!";
  "Volo.Account:ThereIsNoUserWithId": "There is no user with id:{UserId}!";
  "Volo.Account:InvalidAccessToken": "Invalid access_token!";
  "Volo.Account:InvalidTenantIdOrUserId": "Invalid TenantId or UserId!";
  "Volo.Account:InvalidUserDelegationId": "Invalid UserDelegationId!";
  "Volo.Account:DelegatedImpersonationIsDisabled": "Delegated impersonation is disabled!";
  "Volo.Account:UserDelegationIsNotAvailableForImpersonatedUsers": "User delegation is not available for impersonated users!";
  "Volo.Account:ImpersonateError": "Impersonate error!";
  "Volo.Account:StartTimeMustBeLessThanEndTime": "Start time must be less than end time!";
  DelegatedImpersonation: "Delegated impersonation";
  BackToImpersonator: "Back to my account";
  SwitchToUser: "Switch to user";
  ExpiresAt: "Expires at";
  AuthorityDelegation: "Authority delegation";
  DelegateNewUser: "Delegate new user";
  DelegatedUsers: "Delegated users";
  MyDelegatedUsers: "My delegated users";
  DelegationDateRange: "Delegation date range";
  AreYouSure: "Are you sure?";
  StartTime: "Start time";
  EndTime: "End time";
  Status: "Status";
  StatusActive: "Active";
  StatusExpired: "Expired";
  StatusFuture: "Future";
  DeleteUserDelegationConfirmationMessage: "Are you sure you want to delete this delegation '{0}'?";
  "AuthorityDelegation:PleaseSelectUser": "Please select a user";
  "AuthorityDelegation:PleaseSelectDelegationDateRange": "Please select a delegation date range";
  PasswordReset: "Password reset";
  PasswordResetInfoInEmail: "We received an account recovery request! If you initiated this request, click the following link to reset your password.";
  ResetMyPassword: "Reset my password";
  NotAMemberYet: "Not a member yet?";
  OrSignInWith: "Or sign in with";
  EmailConfirmation: "Email confirmation";
  EmailConfirmationInfoInEmail: "Please confirm your email address by clicking the following link.";
  ConfirmMyEmail: "Confirm my email address";
  UserName: "User name";
  EmailAddress: "Email address";
  UserNameOrEmailAddress: "User name or email address";
  Password: "Password";
  RememberMe: "Remember me";
  SelectedProvider: "Selected provider";
  UseAnotherServiceToLogin: "Use another service to log in";
  UserLockedOut: "Locked Out!";
  UserLockedOutMessage: "Your account has been locked by the admin or due to invalid login attempts. Please try again later. Contact your system administrator if you think this is a mistake.";
  InvalidUserNameOrPassword: "Invalid username or password!";
  LoginIsNotAllowed: "You are not allowed to login! Your account is inactive or needs to confirm your email/phone number.";
  SelfRegistrationDisabledMessage: "Self user registration is disabled for this application. Contact to the application administrator to register a new user.";
  VerifySecurityCodeNotLoggedInErrorMessage: "You should be login first, in order to verify yourself! Probably, your login has been timeout. Please go to the login page and re-try it.";
  InvalidSecurityCode: "Invalid security code!";
  EmailSecurityCodeBody: "Your security code is: {0}";
  EmailSecurityCodeSubject: "Security Code";
  VerifySecurityCode_Information: "Please enter the verification code sent to you.";
  SendSecurityCode_Information: "You should verify yourself to login. Please select a verification type. A code will be sent based on the selected verification type.";
  ForgotPassword: "Forgot password?";
  SendPasswordResetLink_Information: "A password reset link will be sent to your email to reset your password. If you don't get an email within a few minutes, please re-try.";
  PasswordResetMailSentMessage: "Account recovery email sent to your e-mail address. If you don't see this email in your inbox within 15 minutes, look for it in your junk mail folder. If you find it there, please mark it as -Not Junk-. ";
  PreventEmailEnumerationPasswordResetMailSentMessage: "If the provided e-mail address is registered in the system, we will send a password reset link. If you don't get an email within a few minutes, please check your spam box or try again later.";
  ResetPassword: "Reset Password";
  ConfirmPassword: "Confirm (repeat) the password";
  ResetPassword_Information: "Please enter your new password.";
  YourPasswordIsSuccessfullyReset: "Your password is successfully reset.";
  YourEmailAddressIsSuccessfullyConfirmed: "Your email address has been successfully confirmed.";
  MailSendingFailed: "Mail sending failed, Please check your email configuration and try again.";
  GoToTheHomePage: "Go to the home page";
  TwoFactorVerification: "Two factor verification";
  BackToLogin: "Back to login";
  AlreadyRegistered: "Already registered?";
  "Permission:Account": "Account";
  "Permission:SettingManagement": "Setting management";
  TwoFactorAuthentication: "Two Factor Authentication";
  "DisplayName:IsSelfRegistrationEnabled": "Enable self registration";
  "Description:IsSelfRegistrationEnabled": "Users can create accounts themselves.";
  "DisplayName:IsRememberBrowserEnabled": "Remember browser";
  "DisplayName:PreventEmailEnumeration": "Prevent email enumeration";
  "Description:PreventEmailEnumeration": "The 'Forgot my password' screen will not return whether the given email is registered in the system or not.";
  "Menu:Account": "Account";
  "Menu:Account.ExternalProvider": "Account external provider";
  AccountSettingsGeneral: "General";
  AccountSettingsTwoFactor: "Two factor";
  TwoFactorHasBeenDisabled: "Two factor has been disabled.";
  "DisplayName:CurrentPassword": "Current password";
  "DisplayName:NewPassword": "New password";
  "DisplayName:NewPasswordConfirm": "Confirm new password";
  PasswordChangedMessage: "Your password has been changed successfully.";
  "DisplayName:UserName": "User name";
  "DisplayName:Email": "Email";
  "DisplayName:Name": "Name";
  "DisplayName:Surname": "Surname";
  "DisplayName:Password": "Password";
  "DisplayName:EmailAddress": "Email address";
  "DisplayName:PhoneNumber": "Phone number";
  "DisplayName:Timezone": "Time zone";
  PersonalSettings: "Personal settings";
  PersonalSettingsSaved: "Personal settings saved";
  PersonalSettingsChangedConfirmationModalTitle: "Personal info changed";
  PersonalSettingsChangedConfirmationModalDescription: "If you want to apply these changes, you have to login. Do you want to log out?";
  PasswordChanged: "Password changed";
  TwoFactorChanged: "Two factor settings saved";
  "DisplayName:TwoFactorEnabled": "Two factor authentication enabled";
  TwoFactorEnabledInfo: "Two factor will be disabled if you remove all two factor providers.";
  YouHaveToEnableAtLeastOneTwoFactorProvider: "You have to enable at least one two factor provider to enable two factor!";
  NewPasswordConfirmFailed: "Please confirm the new password.";
  NewPasswordSameAsOld: "New password must be different from the old one.";
  Manage: "Manage";
  MyAccount: "My account";
  UserInformation: "User information";
  "DisplayName:EnableLocalLogin": "Authenticate with a local account";
  "Description:EnableLocalLogin": "Indicates if Server will allow users to authenticate with a local account.";
  "Feature:AccountGroup": "Account";
  DoYouWantToVerifyPhoneNumberMessage: "You've changed your phone number information. Would you like to verify it now?";
  InvalidPhoneConfirmationToken: "Verify code is invalid!";
  ConfirmYourPhoneNumber: "Verify your phone number";
  Verify: "Verify";
  Verified: "Verified";
  NotVerified: "Not verified";
  FirstlySubmitToVerify: "Firstly save your new information, then you can verify.";
  EmailConfirmationSentMessage: "A verification link has been sent to your email ({0}).";
  ConfirmationTokenSentMessage: "A verification code has been sent to your phone number.";
  PhoneConfirmationToken: "Please enter the code below to verify your phone number:";
  PhoneConfirmationSms: "Hi {0}! Here is your verification code: {1}";
  ConfirmUser: "Confirm your email/phone number";
  PhoneNumberEmptyHelpText: "You don't have a phone number, Verify will set it.";
  "TextTemplate:Abp.Account.Layout": "Account email layout";
  "TextTemplate:Abp.Account.PasswordResetLink": "Password reset email";
  "TextTemplate:Abp.Account.EmailConfirmationLink": "Email confirmation email";
  "TextTemplate:Abp.Account.EmailSecurityCode": "Email security code";
  LoggedOutTitle: "Signed Out";
  LoggedOutText: "You have been signed out and you will be redirected soon.";
  ReturnToText: "Click here to return to the application";
  MySecurityLogs: "Security logs";
  "MySecurityLogs:StartTime": "Start time";
  "MySecurityLogs:EndTime": "End time";
  "MySecurityLogs:Application": "Application";
  "MySecurityLogs:Identity": "Identity";
  "MySecurityLogs:Action": "Action";
  "MySecurityLogs:Client": "Client";
  "MySecurityLogs:Time": "Time";
  "MySecurityLogs:CorrelationId": "CorrelationId";
  "MySecurityLogs:IpAddress": "Ip address";
  "MySecurityLogs:Browser": "Browser";
  LoginToTheApplication: "Login to the application";
  RememberBrowser: "Remember this browser";
  Code: "Code";
  ProfilePicture: "Profile picture";
  MoveCursorOnExamples: "Move your cursor on images to see rounded style.";
  ProfilePictureWillBeChanged: "Your profile picture will be changed.";
  CurrentProfilePicture: "Current profile picture";
  ChangeProfilePicture: "Change profile picture";
  SelectNewImage: "Select new image";
  "DisplayName:UseGravatar": "Use Gravatar";
  "Description:UseGravatar": "Use Gravatar service for your profile picture.";
  SaveChanges: "Save changes";
  UploadFile: "Upload file";
  UseDefault: "Use default avatar";
  UseGravatarConfirm: "You will be using Gravatar as your profile picture.";
  NoProfilePictureConfirm: "You will use default avatar as your profile picture.";
  PPUploadConfirm: "You will use your selected image as your profile picture.";
  PleaseSelectImage: "Please select an image";
  UploadFailedMessage: "Upload failed!";
  "AccountPro:0001": "You must upload an image!";
  "ProfileTab:Picture": "Profile picture";
  "ProfileTab:Password": "Change password";
  "ProfileTab:PersonalInfo": "Personal info";
  "ProfileTab:TwoFactor": "Two factor authentication";
  "ProfileTab:AuthenticatorApp": "Authenticator app";
  "DisplayName:UseCaptchaOnLogin": "Use security image question (captcha) on login.";
  "Description:UseCaptchaOnLogin": "Use security image question (captcha) on login.";
  "DisplayName:UseCaptchaOnRegistration": "Use security image question (captcha) on registration.";
  "Description:UseCaptchaOnRegistration": "Use security image question (captcha) on registration.";
  Captcha: "Captcha";
  "DisplayName:VerifyBaseUrl": "Verify base url";
  "DisplayName:SiteKey": "Site key";
  "DisplayName:SiteSecret": "Site secret";
  "DisplayName:Version": "Version";
  "DisplayName:Score": "Score";
  InvalidSiteKeyOrSiteSecret: "Invalid site key or site secret";
  CaptchaCanNotBeEmpty: "Please check the reCAPTCHA box";
  IncorrectCaptchaAnswer: "Incorrect captcha answer";
  ScoreBelowThreshold: "Verification failed, score below threshold";
  SetNullWillUseGlobalSettings: "Leave as empty to use the defaults";
  ReturnToApplication: "Return to application";
  AccountExternalProviderSettings: "External provider";
  ExternalProviderUseHostSettings: "Use host settings";
  ExternalProviderEnabled: "Enabled";
  LinkedAccounts: "Linked accounts";
  LoginAsThisAccount: "Login as this account";
  DeleteLinkAccountConfirmationMessage: "Are you sure to delete the link account '{0}'?";
  NewLinkAccount: "New link account";
  NewLinkAccountWarning: "You'll be logged out from the current account and logging in with another account. Once you do it, two accounts will be linked.";
  TenantAndUserName: "User name";
  DirectlyLinked: "Directly linked";
  BackToMyAccount: "Back to: {0}";
  LinkLogged: "Accounts are linked";
  StayWithCurrentAccount: "Stay with the current account";
  ReturnToPreviousAccount: "Return to {0} account";
  TheTargetAccountIsNotLinkedToYou: "The target account is not linked to you!";
  LinkAccountWarning: 'Please note that you are linking to other accounts, <a href="{0}">Click here</a> to cancel the link login!';
  SavedSuccessfully: "Saved successfully";
  AccessDenied: "Access denied!";
  AccessDeniedMessage: "You do not have access to this resource.";
  RequestingYourPermission: "is requesting your permission";
  UncheckThePermissionsYouDoNotWishToGrant: "Uncheck the permissions you do not wish to grant.";
  ConsentPersonalInformation: "Personal information";
  ConsentApplicationAccess: "Application access";
  ScopeRequired: "required";
  RememberConsent: "Remember my decision";
  UserDecisionYes: "Yes, allow";
  UserDecisionNo: "No, do not allow";
  DeviceAuthorization: "Device authorization";
  UserCode: "User code";
  UserCodeInvalid: "UserCode invalid!";
  DeviceAuthorizationSuccessfully: "Success!";
  DeviceAuthorizationSuccessfullyInfo: "You have successfully authorized the device";
  LocalLoginIsNotEnabled: "Local login is not enabled!";
  SignIn: "Sign in";
  SignOut: "Sign out";
  Date: "Date";
  ResetAuthenticator: "Reset authenticator";
  ResetAuthenticator_Information: "If you would like to change your authenticator app, you can reset it here.";
  ResetAuthenticatorWarningMessage: "Reset your authenticator key your authenticator app will not work until you reconfigure it.";
  UseTwoFactorAuthenticatorApp_Information: "Open your two factor authentication app and do one of the following actions:";
  UseTwoFactorAuthenticatorApp_Code: "Your two-factor authentication application will generate a code, enter this code in the box below and confirm.";
  RecoveryCode: "Recovery code";
  RecoveryCodes: "Recovery codes";
  RecoveryCodes_Information: "Put these codes in a safe place. If you lose your device and don't have the recovery codes you will lose access to your account.";
  CopyToClipboard: "Copy to clipboard";
  PrintCodes: "Print codes";
  LoginWithRecoveryCode: "Login with recovery code";
  LoginWithRecoveryCode_Information: " You have requested to log in with a recovery code. 'Remember me' will not be enabled for this login until you provide an authenticator app code or disable 2FA and log in again.";
  LoginWithRecoveryCode_URL: "Don't have access to your authenticator device? You can log in with a recovery code";
  UseQrCode: "Use the QR Code";
  ManuallyEnterCode: "Or manually enter the code";
  TwoFactorAuthenticationProviders: "Two-Factor authentication providers";
  AuthenticatorApp: "Authenticator app";
  VerifyTheAuthenticator: "Verify the authenticator";
  Step: "Step {0}";
  NextStep: "Next step";
  Done: "Done";
  ShowPassword: "Show password";
  HidePassword: "Hide password";
  CapsLockOn: "Caps lock on";
  TakePhoto: "Take photo";
  ChoosePhoto: "Choose photo";
  Strength: "Strength";
  Weak: "Weak!";
  Fair: "Fair.";
  Normal: "Normal.";
  Good: "Good.";
  Strong: "Strong!";
  "Authentication:YouAreLoggedOut": "You are logged out.";
  OrRegisterWith: "Or register with";
  RegisterText: 'By clicking Register button, you agree to our <a href="/Account/TermsConditions" target="_blank" class="text-decoration-none" rel="noopener">Terms & Conditions</a> and <a href="/Account/Privacy" target="_blank" class="text-decoration-none" rel="noopener">Privacy Policy</a>.';
};
export type AbpEmailingResources = {
  "DisplayName:Abp.Mailing.DefaultFromAddress": "Default from address";
  "DisplayName:Abp.Mailing.DefaultFromDisplayName": "Default from display name";
  "DisplayName:Abp.Mailing.Smtp.Host": "Host";
  "DisplayName:Abp.Mailing.Smtp.Port": "Port";
  "DisplayName:Abp.Mailing.Smtp.UserName": "User name";
  "DisplayName:Abp.Mailing.Smtp.Password": "Password";
  "DisplayName:Abp.Mailing.Smtp.Domain": "Domain";
  "DisplayName:Abp.Mailing.Smtp.EnableSsl": "Enable SSL";
  "DisplayName:Abp.Mailing.Smtp.UseDefaultCredentials": "Use default credentials";
  "Description:Abp.Mailing.DefaultFromAddress": "The default from address";
  "Description:Abp.Mailing.DefaultFromDisplayName": "The default from display name";
  "Description:Abp.Mailing.Smtp.Host": "The name or IP address of the host used for SMTP transactions.";
  "Description:Abp.Mailing.Smtp.Port": "The port used for SMTP transactions.";
  "Description:Abp.Mailing.Smtp.UserName": "User name associated with the credentials.";
  "Description:Abp.Mailing.Smtp.Password": "The password for the user name associated with the credentials.";
  "Description:Abp.Mailing.Smtp.Domain": "The domain or computer name that verifies the credentials.";
  "Description:Abp.Mailing.Smtp.EnableSsl": "Whether the SmtpClient uses Secure Sockets Layer (SSL) to encrypt the connection.";
  "Description:Abp.Mailing.Smtp.UseDefaultCredentials": "Whether the DefaultCredentials are sent with requests.";
  "TextTemplate:StandardEmailTemplates.Layout": "Default email layout template";
  "TextTemplate:StandardEmailTemplates.Message": "Simple message template for emails";
};
export type AbpUiResources = {
  Languages: "Languages";
  AreYouSure: "Are you sure?";
  Cancel: "Cancel";
  Clear: "Clear";
  Yes: "Yes";
  No: "No";
  Ok: "Ok";
  Close: "Close";
  Save: "Save";
  SavingWithThreeDot: "Saving...";
  Actions: "Actions";
  Delete: "Delete";
  SavedSuccessfully: "Saved successfully";
  DeletedSuccessfully: "Deleted successfully";
  Edit: "Edit";
  Refresh: "Refresh";
  Language: "Language";
  LoadMore: "Load more";
  ProcessingWithThreeDot: "Processing...";
  LoadingWithThreeDot: "Loading...";
  Welcome: "Welcome";
  Login: "Login";
  Register: "Register";
  Logout: "Log out";
  Submit: "Submit";
  Back: "Back";
  PagerSearch: "Search";
  PagerNext: "Next";
  PagerPrevious: "Previous";
  PagerFirst: "First";
  PagerLast: "Last";
  PagerInfo: "Showing _START_ to _END_ of _TOTAL_ entries";
  "PagerInfo{0}{1}{2}": "Showing {0} to {1} of {2} entries";
  PagerInfoEmpty: "Showing 0 to 0 of 0 entries";
  PagerInfoFiltered: "(filtered from _MAX_ total entries)";
  NoDataAvailableInDatatable: "No data available";
  Total: "total";
  Selected: "selected";
  PagerShowMenuEntries: "Show _MENU_ entries";
  DatatableActionDropdownDefaultText: "Actions";
  ChangePassword: "Change password";
  PersonalInfo: "My profile";
  AreYouSureYouWantToCancelEditingWarningMessage: "You have unsaved changes.";
  GoHomePage: "Go to the homepage";
  GoBack: "Go back";
  Search: "Search";
  ItemWillBeDeletedMessageWithFormat: "{0} will be deleted!";
  ItemWillBeDeletedMessage: "This item will be deleted!";
  ManageYourAccount: "Manage your account";
  OthersGroup: "Other";
  Today: "Today";
  Apply: "Apply";
  InternetConnectionInfo: "The operation could not be performed. Your internet connection is not available at the moment.";
  CopiedToTheClipboard: "Copied to the clipboard";
  AddNew: "Add new";
  ProfilePicture: "Profile picture";
  Theme: "Theme";
  NotAssigned: "Not Assigned";
};
export type AbpUiNavigationResources = {
  "Menu:Administration": "Administration";
};
export type AbpUiMultiTenancyResources = {
  GivenTenantIsNotExist: "Given tenant doesn't exist: {0}";
  GivenTenantIsNotAvailable: "Given tenant isn't available: {0}";
  Tenant: "Tenant";
  Switch: "switch";
  Name: "Name";
  SwitchTenantHint: "Leave the name field blank to switch to the host side.";
  SwitchTenant: "Switch tenant";
  NotSelected: "Not selected";
};
export type LeptonXResources = {
  Login: "Login";
  Appearance: "Appearance";
  ContainerWidth: "Container Width";
  "ContainerWidth:Boxed": "Boxed Layout";
  "ContainerWidth:Fixed": "Fixed";
  "ContainerWidth:Fluid": "Fluid";
  GeneralSettings: "General Settings";
  Language: "Language";
  Settings: "Settings";
  "Theme:dark": "Dark";
  "Theme:dim": "Semi-Dark";
  "Theme:light": "Light";
  "Theme:system": "System";
  Welcome: "Welcome";
  FilterMenu: "Filter Menu";
  "Authentication:YouAreLoggedOut": "You are logged out.";
  GivenTenantIsNotExist: "Given tenant doesn't exist: {0}";
  GivenTenantIsNotAvailable: "Given tenant isn't available: {0}";
  Tenant: "Tenant";
  Switch: "switch";
  Name: "Name";
  SwitchTenantHint: "Leave the name field blank to switch to the host side.";
  SwitchTenant: "Switch tenant";
  NotSelected: "Not selected";
};
